import React, { useEffect, useState } from "react";
import { UserCheck, Clock3 } from "lucide-react";
import { apiRequest } from "../../lib/api";
import { EmptyState, ErrorState, LoadingState } from "../../components/AsyncState";

export default function GymCheckins() {
  const [members, setMembers] = useState([]), [checkins, setCheckins] = useState([]), [memberId, setMemberId] = useState("");
  const [status, setStatus] = useState({ loading: true, saving: false, error: "" });
  async function load() { setStatus((s) => ({ ...s, loading: true, error: "" })); try { const [membersRes, checkinsRes] = await Promise.all([apiRequest("/gym/members"), apiRequest("/gym/checkins?limit=100")]); setMembers(membersRes.data || []); setCheckins(checkinsRes.data || []); } catch (error) { setStatus((s) => ({ ...s, error: error.message })); } finally { setStatus((s) => ({ ...s, loading: false })); } }
  useEffect(() => { load(); }, []);
  async function handleCheckin(e) { e.preventDefault(); if (!memberId) return; setStatus((s) => ({ ...s, saving: true, error: "" })); try { await apiRequest("/gym/checkins", { method: "POST", body: JSON.stringify({ member_id: memberId }) }); setMemberId(""); await load(); } catch (error) { setStatus((s) => ({ ...s, error: error.message })); } finally { setStatus((s) => ({ ...s, saving: false })); } }
  if (status.loading) return <LoadingState />;
  return <div className="space-y-5 motion-card">
    <div className="rounded-2xl border border-emerald-100 bg-gradient-to-r from-white via-emerald-50/50 to-blue-50 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Daily attendance</p><div className="mt-1 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black">Check-ins</h2><p className="text-sm text-slate-500">Record arrivals instantly and keep a live attendance history.</p></div><div className="rounded-xl bg-white px-4 py-3 text-center shadow-sm ring-1 ring-emerald-100"><p className="text-xs font-semibold text-slate-500">Recent check-ins</p><p className="text-xl font-black text-emerald-600">{checkins.length}</p></div></div></div>
    {status.error && <ErrorState message={status.error} />}
    <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={handleCheckin} className="panel h-fit p-5 transition duration-300 hover:-translate-y-0.5 hover:shadow-md"><h2 className="mb-4 flex items-center gap-2 text-lg font-black"><UserCheck className="h-5 w-5 text-blue-600" /> Check a member in</h2><select className="field" value={memberId} onChange={(e) => setMemberId(e.target.value)} required><option value="">Choose member…</option>{members.filter((m) => !m.status || m.status === "active").map((m) => <option key={m.id} value={m.id}>{m.name}{m.gender ? ` (${m.gender === "female" ? "Women" : "Men"})` : ""}</option>)}</select><button className="btn-primary mt-4 w-full" disabled={status.saving || !memberId}>{status.saving ? "Checking in…" : "Check in"}</button></form>
      <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Live history</p><h2 className="text-base font-black">Who came, and when</h2></div><Clock3 className="h-5 w-5 text-slate-400" /></div>{checkins.length === 0 ? <div className="flex min-h-[300px] items-center justify-center p-8"><EmptyState title="No check-ins yet" description="Check a member in above to see the attendance timeline appear here." /></div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Member</th><th className="px-4 py-3">Checked in</th></tr></thead><tbody className="divide-y divide-slate-100">{checkins.map((c) => <tr key={c.id} className="transition hover:bg-emerald-50/40"><td className="px-4 py-3 font-bold">{c.gym_members?.name || "-"}</td><td className="px-4 py-3 text-slate-500">{c.checked_in_at ? new Date(c.checked_in_at).toLocaleString() : "-"}</td></tr>)}</tbody></table></div>}</div>
    </div>
  </div>;
}
