import React, { useEffect, useState } from "react";
import { Wallet } from "lucide-react";
import { apiRequest, formatMoney } from "../../lib/api";
import { EmptyState, ErrorState, LoadingState } from "../../components/AsyncState";

export default function GymPayments() {
  const [members, setMembers] = useState([]); const [payments, setPayments] = useState([]);
  const [form, setForm] = useState({ member_id: "", amount: "", payment_method: "cash", paid_for_month: "", extend_paid_until: "" });
  const [status, setStatus] = useState({ loading: true, saving: false, error: "" });
  async function load() { setStatus((s) => ({ ...s, loading: true, error: "" })); try { const [m, p] = await Promise.all([apiRequest("/gym/members"), apiRequest("/gym/payments")]); setMembers(m.data || []); setPayments(p.data || []); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, loading: false })); } }
  useEffect(() => { load(); }, []);
  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  async function submit(e) { e.preventDefault(); setStatus((s) => ({ ...s, saving: true, error: "" })); try { await apiRequest("/gym/payments", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount), paid_for_month: form.paid_for_month || undefined, extend_paid_until: form.extend_paid_until || undefined }) }); setForm({ member_id: "", amount: "", payment_method: "cash", paid_for_month: "", extend_paid_until: "" }); await load(); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, saving: false })); } }
  if (status.loading) return <LoadingState />;
  return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="panel h-fit p-4"><h2 className="mb-4 flex items-center gap-2 text-base font-bold"><Wallet className="h-5 w-5 text-blue-600" /> Record a payment</h2>{status.error ? <ErrorState message={status.error} /> : null}<div className="space-y-3"><select className="field" value={form.member_id} onChange={(e) => set("member_id", e.target.value)} required><option value="">Choose member…</option>{members.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input className="field" type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /><select className="field" value={form.payment_method} onChange={(e) => set("payment_method", e.target.value)}><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_money">Mobile money</option></select><input className="field" type="date" value={form.paid_for_month} onChange={(e) => set("paid_for_month", e.target.value)} /><div><label className="mb-1 block text-xs font-semibold text-slate-500">Extend paid-until</label><input className="field" type="date" value={form.extend_paid_until} onChange={(e) => set("extend_paid_until", e.target.value)} /></div></div><button className="btn-primary mt-4 w-full" disabled={status.saving}>{status.saving ? "Saving…" : "Record payment"}</button></form><div className="panel overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="text-base font-bold">Payment history</h2></div>{payments.length === 0 ? <div className="p-4"><EmptyState title="No payments yet" description="Record a membership payment to see it here." /></div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Member</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Paid</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((p) => <tr key={p.id}><td className="px-4 py-3 font-semibold">{p.gym_members?.name || "-"}</td><td className="px-4 py-3 capitalize">{p.payment_method}</td><td className="px-4 py-3">{p.paid_at ? new Date(p.paid_at).toLocaleDateString() : "-"}</td><td className="px-4 py-3 text-right font-bold">{formatMoney(p.amount)}</td></tr>)}</tbody></table></div>}</div></div>;
}
