import React, { useEffect, useState } from "react";
import { Wallet } from "lucide-react";
import EntityCrud from "../../components/EntityCrud";
import { apiRequest, formatMoney } from "../../lib/api";
import { EmptyState, ErrorState, LoadingState } from "../../components/AsyncState";

function SalaryPayments() {
  const [staff, setStaff] = useState([]), [payments, setPayments] = useState([]);
  const [form, setForm] = useState({ staff_id: "", amount: "", paid_for_month: "", notes: "" });
  const [status, setStatus] = useState({ loading: true, saving: false, error: "" });
  async function load() { setStatus((s) => ({ ...s, loading: true, error: "" })); try { const [s, p] = await Promise.all([apiRequest("/staff"), apiRequest("/gym/staff-payments")]); setStaff(s.data || []); setPayments(p.data || []); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, loading: false })); } }
  useEffect(() => { load(); }, []); const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  async function submit(e) { e.preventDefault(); setStatus((s) => ({ ...s, saving: true, error: "" })); try { await apiRequest("/gym/staff-payments", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount), paid_for_month: form.paid_for_month || undefined }) }); setForm({ staff_id: "", amount: "", paid_for_month: "", notes: "" }); await load(); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, saving: false })); } }
  if (status.loading) return <LoadingState />;
  return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="panel h-fit p-4"><h2 className="mb-4 flex items-center gap-2 text-base font-bold"><Wallet className="h-5 w-5 text-blue-600" /> Pay a staff member</h2>{status.error ? <ErrorState message={status.error} /> : null}<div className="space-y-3"><select className="field" value={form.staff_id} onChange={(e) => set("staff_id", e.target.value)} required><option value="">Choose staff…</option>{staff.map((s) => <option key={s.id} value={s.id}>{s.name} ({s.role})</option>)}</select><input className="field" type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /><input className="field" type="date" value={form.paid_for_month} onChange={(e) => set("paid_for_month", e.target.value)} /><input className="field" placeholder="Notes" value={form.notes} onChange={(e) => set("notes", e.target.value)} /></div><button className="btn-primary mt-4 w-full" disabled={status.saving}>{status.saving ? "Saving…" : "Record payment"}</button></form><div className="panel overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="text-base font-bold">Salary payment history</h2></div>{payments.length === 0 ? <div className="p-4"><EmptyState title="No payments yet" description="Pay a staff member to see it here." /></div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Staff</th><th className="px-4 py-3">Paid</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((p) => <tr key={p.id}><td className="px-4 py-3 font-semibold">{p.staff?.name || "-"}</td><td className="px-4 py-3">{p.paid_at ? new Date(p.paid_at).toLocaleDateString() : "-"}</td><td className="px-4 py-3 text-right font-bold">{formatMoney(p.amount)}</td></tr>)}</tbody></table></div>}</div></div>;
}
export default function GymStaff() { const [tab, setTab] = useState("people"); return <div className="space-y-4"><div className="flex w-fit rounded-full bg-slate-100 p-1">{[["people", "Staff"], ["payments", "Salary Payments"]].map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab === key ? "bg-blue-600 text-white" : "text-slate-500"}`}>{label}</button>)}</div>{tab === "people" ? <EntityCrud apiPath="/staff" title="Add Staff Member" emptyTitle="No staff yet" emptyDescription="Add trainers, front desk staff, cleaners, and managers." fields={[{ key: "name", label: "Full name", required: true }, { key: "email", label: "Email (optional)" }, { key: "role", label: "Role", type: "select", default: "staff", options: [{ value: "staff", label: "Staff" }, { value: "manager", label: "Manager" }] }]} columns={[{ key: "name", label: "Name" }, { key: "email", label: "Email" }, { key: "role", label: "Role", render: (r) => <span className="capitalize">{r.role}</span> }, { key: "status", label: "Status", render: (r) => <span className="rounded-full px-2 py-0.5 text-xs font-bold">{r.status || "active"}</span> }]} /> : <SalaryPayments />}</div>; }
