import React, { useEffect, useState } from "react";
import { ClipboardCheck, Trash2, Save, X } from "lucide-react";
import { apiRequest } from "../../lib/api";
import { EmptyState, ErrorState, LoadingState } from "../../components/AsyncState";

function ResultsEntry({ exam, onClose }) {
  const [students, setStudents] = useState([]), [scores, setScores] = useState({});
  const [status, setStatus] = useState({ loading: true, saving: false, error: "", success: "" });
  useEffect(() => { (async () => { try { const [s, r] = await Promise.all([apiRequest(`/school/students${exam.class_id ? `?class_id=${exam.class_id}` : ""}`), apiRequest(`/school/exams/${exam.id}/results`)]); setStudents(s.data || []); const map = {}; (r.data || []).forEach((x) => { map[x.student_id] = x.score; }); setScores(map); } catch (e) { setStatus((x) => ({ ...x, error: e.message })); } finally { setStatus((x) => ({ ...x, loading: false })); } })(); }, [exam.id, exam.class_id]);
  const save = async () => { setStatus((s) => ({ ...s, saving: true, error: "", success: "" })); try { const results = Object.entries(scores).filter(([, v]) => v !== "" && v != null).map(([student_id, score]) => ({ student_id, score: Number(score) })); await apiRequest(`/school/exams/${exam.id}/results`, { method: "POST", body: JSON.stringify({ results }) }); setStatus((s) => ({ ...s, saving: false, success: "Results saved successfully." })); } catch (e) { setStatus((s) => ({ ...s, saving: false, error: e.message })); } };
  if (status.loading) return <LoadingState />;
  return <div className="motion-pop space-y-5"><div className="rounded-2xl border border-blue-100 bg-gradient-to-r from-white via-blue-50/50 to-indigo-50 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Grade entry</p><h2 className="mt-1 text-2xl font-black">{exam.name}</h2><p className="text-sm text-slate-500">Enter scores for each student. Maximum score: {exam.max_score}.</p></div><button className="btn-secondary" onClick={onClose}><X className="h-4 w-4" /> Close</button></div></div>{status.error && <ErrorState message={status.error} />}{status.success && <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{status.success}</div>}<div className="panel p-5">{students.length === 0 ? <EmptyState title="No students in this class" description="Assign students to this exam's class first." /> : <div className="space-y-2">{students.map((s) => <div key={s.id} className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50/60 px-4 py-3 transition hover:-translate-y-0.5 hover:bg-blue-50/50"><span className="font-bold">{s.name}</span><input type="number" min="0" max={exam.max_score} className="field w-28 text-right" value={scores[s.id] ?? ""} onChange={(e) => setScores((sc) => ({ ...sc, [s.id]: e.target.value }))} /></div>)}<button className="btn-primary mt-3" onClick={save} disabled={status.saving}><Save className="h-4 w-4" />{status.saving ? "Saving…" : "Save results"}</button></div>}</div></div>;
}

export default function SchoolExams() {
  const [exams, setExams] = useState([]), [classes, setClasses] = useState([]), [openExam, setOpenExam] = useState(null);
  const [form, setForm] = useState({ name: "", class_id: "", exam_date: "", max_score: "100" });
  const [status, setStatus] = useState({ loading: true, saving: false, error: "" });
  const load = async () => { setStatus((s) => ({ ...s, loading: true, error: "" })); try { const [e, c] = await Promise.all([apiRequest("/school/exams"), apiRequest("/school/classes")]); setExams(e.data || []); setClasses(c.data || []); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, loading: false })); } };
  useEffect(() => { load(); }, []);
  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  const submit = async (e) => { e.preventDefault(); setStatus((s) => ({ ...s, saving: true, error: "" })); try { await apiRequest("/school/exams", { method: "POST", body: JSON.stringify({ ...form, max_score: Number(form.max_score) || 100 }) }); setForm({ name: "", class_id: "", exam_date: "", max_score: "100" }); await load(); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, saving: false })); } };
  const del = async (id) => { if (!window.confirm("Remove this exam and all its results?")) return; try { await apiRequest(`/school/exams/${id}`, { method: "DELETE" }); await load(); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } };
  if (status.loading) return <LoadingState />;
  if (openExam) return <ResultsEntry exam={openExam} onClose={() => setOpenExam(null)} />;
  return <div className="space-y-5 motion-card"><div className="rounded-2xl border border-violet-100 bg-gradient-to-r from-white via-violet-50/50 to-blue-50 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Academic assessment</p><h2 className="mt-1 text-2xl font-black">Exams & results</h2><p className="mt-1 text-sm text-slate-500">Create exams, open a class roster, and enter results without leaving the page.</p></div>{status.error && <ErrorState message={status.error} />}<div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="panel h-fit p-5 transition duration-300 hover:-translate-y-0.5 hover:shadow-md"><h2 className="mb-4 flex items-center gap-2 text-lg font-black"><ClipboardCheck className="h-5 w-5 text-violet-600" /> Add Exam</h2><div className="space-y-3"><input className="field" placeholder="Exam name" value={form.name} onChange={(e) => set("name", e.target.value)} required /><select className="field" value={form.class_id} onChange={(e) => set("class_id", e.target.value)}><option value="">Choose class</option>{classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field" type="date" value={form.exam_date} onChange={(e) => set("exam_date", e.target.value)} /><input className="field" type="number" min="1" value={form.max_score} onChange={(e) => set("max_score", e.target.value)} /></div><button className="btn-primary mt-4 w-full" disabled={status.saving}>{status.saving ? "Saving…" : "Add exam"}</button></form><div className="panel min-h-[360px] overflow-hidden">{exams.length === 0 ? <div className="flex min-h-[360px] items-center justify-center p-8"><EmptyState title="No exams yet" description="Add your first exam, then enter student scores." /></div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="px-4 py-3">Exam</th><th className="px-4 py-3">Class</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{exams.map((ex) => <tr key={ex.id} className="transition hover:bg-violet-50/40"><td className="px-4 py-3 font-bold">{ex.name}</td><td className="px-4 py-3">{ex.school_classes?.name || "-"}</td><td className="px-4 py-3">{ex.exam_date ? new Date(ex.exam_date).toLocaleDateString() : "-"}</td><td className="px-4 py-3 text-right"><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setOpenExam(ex)}>Enter scores</button><button type="button" className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-red-100 text-red-600 transition hover:-translate-y-0.5 hover:bg-red-50" onClick={() => del(ex.id)}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>}</div></div></div>;
}
