import React, { useEffect, useState } from "react";
import EntityCrud from "../../components/EntityCrud";
import { apiRequest, formatMoney } from "../../lib/api";
import { Wallet, AlertTriangle } from "lucide-react";
import { EmptyState, ErrorState, LoadingState } from "../../components/AsyncState";

function SalaryPayments() {
  const [teachers, setTeachers] = useState([]), [payments, setPayments] = useState([]), [unpaid, setUnpaid] = useState([]);
  const [form, setForm] = useState({ teacher_id: "", amount: "", paid_for_month: "" });
  const [status, setStatus] = useState({ loading: true, saving: false, error: "" });
  const load = async () => { setStatus((s) => ({ ...s, loading: true, error: "" })); try { const [t, p, u] = await Promise.all([apiRequest("/school/teachers"), apiRequest("/school/salary-payments"), apiRequest("/school/salary-payments/unpaid")]); setTeachers(t.data || []); setPayments(p.data || []); setUnpaid(u.data || []); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, loading: false })); } };
  useEffect(() => { load(); }, []);
  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  async function submit(e) { e.preventDefault(); setStatus((s) => ({ ...s, saving: true, error: "" })); try { await apiRequest("/school/salary-payments", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount), paid_for_month: form.paid_for_month || undefined }) }); setForm({ teacher_id: "", amount: "", paid_for_month: "" }); await load(); } catch (e) { setStatus((s) => ({ ...s, error: e.message })); } finally { setStatus((s) => ({ ...s, saving: false })); } }
  if (status.loading) return <LoadingState />;
  return <div className="space-y-5 motion-card">{unpaid.length > 0 && <div className="rounded-2xl border border-amber-100 bg-gradient-to-r from-amber-50 to-white p-5"><h2 className="mb-3 flex items-center gap-2 font-black"><AlertTriangle className="h-5 w-5 text-amber-500" /> Not paid this month</h2><div className="flex flex-wrap gap-2">{unpaid.map((t) => <span key={t.id} className="rounded-full bg-white px-3 py-1.5 text-sm font-semibold text-amber-800 shadow-sm ring-1 ring-amber-100">{t.name} — {formatMoney(t.monthly_salary)}</span>)}</div></div>}{status.error && <ErrorState message={status.error} />}<div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="panel h-fit p-5 transition duration-300 hover:-translate-y-0.5 hover:shadow-md"><h2 className="mb-4 flex items-center gap-2 text-lg font-black"><Wallet className="h-5 w-5 text-blue-600" /> Pay a teacher</h2><div className="space-y-3"><select className="field" value={form.teacher_id} onChange={(e) => set("teacher_id", e.target.value)} required><option value="">Choose teacher…</option>{teachers.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><input className="field" type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /><input className="field" type="date" value={form.paid_for_month} onChange={(e) => set("paid_for_month", e.target.value)} /></div><button className="btn-primary mt-4 w-full" disabled={status.saving}>{status.saving ? "Saving…" : "Record payment"}</button></form><div className="panel overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="font-black">Salary payment history</h2></div>{payments.length === 0 ? <div className="p-6"><EmptyState title="No payments yet" description="Pay a teacher to see it here." /></div> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase"><tr><th className="px-4 py-3">Teacher</th><th className="px-4 py-3">Paid</th><th className="px-4 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((p) => <tr key={p.id} className="transition hover:bg-blue-50/40"><td className="px-4 py-3 font-semibold">{p.school_teachers?.name || "-"}</td><td className="px-4 py-3">{p.paid_at ? new Date(p.paid_at).toLocaleDateString() : "-"}</td><td className="px-4 py-3 text-right font-bold">{formatMoney(p.amount)}</td></tr>)}</tbody></table></div>}</div></div></div>;
}

export default function SchoolTeachers() {
  const [tab, setTab] = useState("people");
  return <div className="space-y-4 motion-card"><div className="flex w-fit rounded-xl bg-slate-100 p-1 shadow-sm">{[["people", "Teachers"], ["salaries", "Salary Payments"]].map(([k, l]) => <button key={k} onClick={() => setTab(k)} className={`rounded-lg px-4 py-2 text-sm font-bold transition ${tab === k ? "bg-white text-blue-700 shadow-sm" : "text-slate-500 hover:text-slate-800"}`}>{l}</button>)}</div>{tab === "people" ? <EntityCrud apiPath="/school/teachers" title="Add Teacher" entityLabel="teachers" emptyTitle="No teachers yet" emptyDescription="Add your teachers individually or register several at once." fields={[{ key: "name", label: "Full name", required: true }, { key: "phone", label: "Phone number" }, { key: "subject", label: "Subject" }, { key: "monthly_salary", label: "Monthly salary", type: "number" }]} columns={[{ key: "name", label: "Name" }, { key: "subject", label: "Subject" }, { key: "phone", label: "Phone" }, { key: "monthly_salary", label: "Salary", align: "right", render: (r) => formatMoney(r.monthly_salary) }, { key: "status", label: "Status", render: (r) => <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{r.status || "active"}</span> }]} /> : <SalaryPayments />}</div>;
}
