import React,{useState} from "react";
import {Link,useLocation,useNavigate} from "react-router-dom";
import {ArrowRight,Eye,EyeOff,Mail,UserRound,ShieldCheck,LockKeyhole} from "lucide-react";
import {apiRequest} from "../lib/api";
import {saveSession} from "../lib/auth";
import {supabase} from "../lib/supabaseClient";
import sahelLogo from "../assets/sahel_logo_english.svg";

const COPY={
 en:{login:"Welcome back",signup:"Create your Sahel account",loginSub:"Sign in and Sahel will take you straight to your saved workspace.",signupSub:"Create your account first. We’ll ask a few workspace questions next — not on this page.",fullName:"Full name",email:"Email address",password:"Password",namePlaceholder:"e.g. Abdikadir Artan",emailPlaceholder:"you@example.com",create:"Create account",signIn:"Sign in",google:"Continue with Google",or:"or",forgot:"Forgot password?",new:"New to Sahel?",existing:"Already have an account?",switchToCreate:"Create account",secure:"Your account is protected. Your workspace is configured after signup.",automatic:"Automatic workspace routing",automaticSub:"After setup, you will never need to choose Shop, School, Gym, or Hospital just to log in.",show:"Show password",hide:"Hide password"},
 so:{login:"Ku soo dhowow",signup:"Samee akoonka Sahel",loginSub:"Gal akoonkaaga, Sahel-na si toos ah ayuu kuu geynayaa goobtaada.",signupSub:"Marka hore samee akoonkaaga. Kadib waxaan ku weydiin doonaa dhowr su’aalood oo ku saabsan goobtaada — ma aha boggan.",fullName:"Magaca oo buuxa",email:"Email-ka",password:"Erayga sirta ah",namePlaceholder:"tusaale: Abdikadir Artan",emailPlaceholder:"you@example.com",create:"Samee akoon",signIn:"Gal",google:"Google ku sii wad",or:"ama",forgot:"Ma ilowday erayga sirta ah?",new:"Sahel ma ku cusub tahay?",existing:"Akoon ma leedahay?",switchToCreate:"Samee akoon",secure:"Akoonkaaga waa la ilaaliyaa. Goobtaada waxaa la dejinayaa kadib signup.",automatic:"Goobta si toos ah ayaa loo aqoonsanayaa",automaticSub:"Kadib dejinta, uma baahnid inaad doorato Shop, Gym, School ama Hospital markaad galeyso.",show:"Muuji erayga sirta",hide:"Qari erayga sirta"}
};
function Field({icon:Icon,label,...props}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><span className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3.5 transition focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-50"><Icon className="h-4 w-4 text-slate-400"/><input className="w-full bg-transparent text-sm font-medium text-slate-900 outline-none placeholder:text-slate-400" {...props}/></span></label>}
export default function AuthPageV2({mode}){
 const signup=mode==="signup";const navigate=useNavigate(),location=useLocation();const [lang,setLang]=useState("en"),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");const [form,setForm]=useState({full_name:"",email:"",password:""});const t=COPY[lang];const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function submit(e){e.preventDefault();setError("");setLoading(true);try{const body=signup?form:{email:form.email,password:form.password};const response=await apiRequest(signup?"/auth/signup":"/auth/login",{method:"POST",body:JSON.stringify(body)});saveSession(response.data);navigate(response.data.onboarding_required?"/onboarding":(location.state?.from||"/dashboard"),{replace:true});}catch(err){setError(err.message||"Something went wrong. Please try again.")}finally{setLoading(false)}}
 async function google(){setError("");localStorage.setItem("sahel_google_flow",signup?"signup":"login");localStorage.removeItem("sahel_google_business_type");setLoading(true);try{const {error:e}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/auth/callback"}});if(e)throw e}catch(e){setError(e.message||"Google sign-in failed.");setLoading(false)}}
 return <main className="min-h-screen bg-[#f6f8fc] text-slate-900"><div className="mx-auto grid min-h-screen max-w-7xl lg:grid-cols-[1.08fr_.92fr]">
  <aside className="relative hidden overflow-hidden bg-gradient-to-br from-blue-700 via-blue-700 to-indigo-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-white/10 blur-3xl"/><div><img src={sahelLogo} className="h-9 brightness-0 invert" alt="Sahel"/><div className="mt-24 max-w-xl"><p className="text-sm font-black uppercase tracking-[.2em] text-blue-200">One account. One workspace.</p><h1 className="mt-5 text-5xl font-black leading-[1.05]">Manage your organization without the setup clutter.</h1><p className="mt-6 text-lg leading-8 text-blue-100">Create your account first. Then tell Sahel what you manage and what you need. We use those answers to configure your workspace.</p></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><ShieldCheck className="mb-3 h-5 w-5 text-blue-200"/><p className="text-sm font-bold">Secure account</p><p className="mt-1 text-xs text-blue-100">Protected sign-in and session routing.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><LockKeyhole className="mb-3 h-5 w-5 text-blue-200"/><p className="text-sm font-bold">Smart setup</p><p className="mt-1 text-xs text-blue-100">Workspace questions come after signup.</p></div></div></aside>
  <section className="flex items-center justify-center p-5 sm:p-8"><div className="w-full max-w-md"><div className="mb-6 flex items-center justify-between"><Link to="/welcome"><img src={sahelLogo} className="h-8 lg:hidden" alt="Sahel"/></Link><div className="ml-auto flex rounded-full bg-white p-1 shadow-sm">{["en","so"].map(x=><button key={x} onClick={()=>setLang(x)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${lang===x?"bg-blue-600 text-white":"text-slate-500"}`}>{x.toUpperCase()}</button>)}</div></div>
   <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_30px_90px_rgba(15,23,42,.09)] sm:p-9"><div className="mb-8"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50"><img src={sahelLogo} className="h-7" alt="Sahel"/></div><h2 className="text-3xl font-black tracking-tight">{signup?t.signup:t.login}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{signup?t.signupSub:t.loginSub}</p></div>
    {!signup&&<div className="mb-6 flex items-start gap-3 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-blue-600 shadow-sm"><LockKeyhole className="h-4 w-4"/></div><div><p className="text-sm font-black text-slate-900">{t.automatic}</p><p className="mt-1 text-xs leading-5 text-slate-600">{t.automaticSub}</p></div></div>}
    <form onSubmit={submit} className="space-y-4">{signup&&<Field icon={UserRound} label={t.fullName} placeholder={t.namePlaceholder} value={form.full_name} onChange={e=>set("full_name",e.target.value)} autoComplete="name"/>}<Field icon={Mail} label={t.email} type="email" placeholder={t.emailPlaceholder} value={form.email} onChange={e=>set("email",e.target.value)} autoComplete="email" required/><label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{t.password}</span><span className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3.5 focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-50"><input className="w-full bg-transparent text-sm font-medium outline-none" type={show?"text":"password"} value={form.password} onChange={e=>set("password",e.target.value)} minLength={8} autoComplete={signup?"new-password":"current-password"} required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?t.hide:t.show}>{show?<EyeOff className="h-4 w-4 text-slate-400"/>:<Eye className="h-4 w-4 text-slate-400"/>}</button></span></label>{error&&<div className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold leading-5 text-red-700">{error}</div>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-black text-white shadow-lg shadow-blue-200 transition hover:bg-blue-700 disabled:opacity-60">{loading?"Please wait…":signup?t.create:t.signIn}<ArrowRight className="h-4 w-4"/></button></form>
    <div className="my-6 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200"/><span className="text-xs font-bold uppercase text-slate-400">{t.or}</span><div className="h-px flex-1 bg-slate-200"/></div><button onClick={google} disabled={loading} className="flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white text-sm font-bold transition hover:bg-slate-50"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-slate-200 text-xs font-black">G</span>{t.google}</button>
    <div className="mt-6 text-center text-sm text-slate-500">{signup?t.existing:t.new} <Link className="font-black text-blue-600 hover:underline" to={signup?"/login":"/signup"}>{signup?t.signIn:t.switchToCreate}</Link>{!signup&&<><span className="mx-2 text-slate-300">·</span><Link className="font-bold text-slate-600 hover:text-blue-600" to="/forgot-password">{t.forgot}</Link></>}</div><p className="mt-6 text-center text-xs font-medium text-slate-400">{t.secure}</p>
   </div></div></section></div></main>
}
