import React, { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Check, ChevronDown, Dumbbell, GraduationCap, Menu, Package, ReceiptText, ShieldCheck, Store, Users, WalletCards, X } from "lucide-react";
import sahelLogo from "../assets/sahel_logo_english.svg";

const verticals=[
 {icon:Store,title:"Retail & shops",text:"Sales, inventory, customer credit, expenses and receipts in one place.",items:["Sales & receipts","Inventory","Customer credit"]},
 {icon:GraduationCap,title:"Schools",text:"A focused workspace for students, teachers, classes, fees and school records.",items:["Students & teachers","Classes & fees","School records"]},
 {icon:Dumbbell,title:"Gyms",text:"Keep members, check-ins, payments and staff organized without spreadsheets.",items:["Member management","Check-ins","Payments & staff"]}
];
const features=[
 [ReceiptText,"Sales & receipts","Create clear receipts and keep a reliable daily sales history."],
 [Package,"Inventory","Know what you have, what is moving and what needs attention."],
 [Users,"Customers & members","Keep important people, balances and activity organized."],
 [WalletCards,"Payments & fees","Track payments, outstanding balances and recurring dues."],
 [BarChart3,"Reports","Turn daily records into simple information you can act on."],
 [ShieldCheck,"Secure workspace","Keep your organization in one controlled, professional workspace."]
];
export default function LandingV2(){const [menu,setMenu]=useState(false);return <main className="min-h-screen bg-white text-slate-950">
 <header className="sticky top-0 z-40 border-b border-slate-100 bg-white/90 backdrop-blur"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/welcome"><img src={sahelLogo} className="h-8" alt="Sahel"/></Link><nav className="hidden items-center gap-8 text-sm font-bold text-slate-600 md:flex"><a href="#features">Features</a><a href="#businesses">Businesses</a><a href="#how">How it works</a><a href="#faq">FAQ</a></nav><div className="hidden items-center gap-3 md:flex"><Link to="/login" className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Log in</Link><Link to="/signup" className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white shadow-lg shadow-blue-200 hover:bg-blue-700">Get started</Link></div><button className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="border-t border-slate-100 bg-white p-5 md:hidden"><div className="grid gap-3 text-sm font-bold"><a href="#features" onClick={()=>setMenu(false)}>Features</a><a href="#businesses" onClick={()=>setMenu(false)}>Businesses</a><a href="#how" onClick={()=>setMenu(false)}>How it works</a><Link to="/login">Log in</Link><Link to="/signup" className="rounded-xl bg-blue-600 px-4 py-3 text-center text-white">Get started</Link></div></div>}</header>
 <section className="relative overflow-hidden bg-[#f7f9fd]"><div className="absolute -left-32 top-0 h-80 w-80 rounded-full bg-blue-200/40 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-black text-blue-700 shadow-sm"><span className="h-2 w-2 rounded-full bg-blue-600"/> Business management for growing organizations</div><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.04] tracking-tight sm:text-6xl">One platform.<br/><span className="text-blue-600">Built around your work.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Sahel brings the right tools to shops, schools and gyms—so you can manage daily operations without forcing every organization into the same dashboard.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-black text-white shadow-xl shadow-blue-200 hover:bg-blue-700">Create your workspace <ArrowRight className="h-4 w-4"/></Link><a href="#businesses" className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 hover:bg-slate-50">See what Sahel supports</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-bold text-slate-500"><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-blue-600"/> Mobile ready</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-blue-600"/> English & Somali</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-blue-600"/> One organized workspace</span></div></div>
 <div className="relative rounded-[2rem] border border-slate-200 bg-white p-5 shadow-[0_30px_90px_rgba(15,23,42,.12)]"><div className="rounded-2xl bg-slate-50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">Business overview</p><p className="mt-1 text-xl font-black">Today at a glance</p></div><div className="rounded-xl bg-blue-600 p-2 text-white"><BarChart3 className="h-5 w-5"/></div></div><div className="mt-5 grid grid-cols-3 gap-3">{[["Sales","$1,840"],["Stock","$12,480"],["Credit","$2,160"]].map(([a,b])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-[10px] font-bold text-slate-400">{a}</p><p className="mt-1 text-sm font-black">{b}</p></div>)}</div><div className="mt-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-500">Weekly performance</p><span className="text-xs font-black text-blue-600">+12.4%</span></div><div className="mt-5 flex h-24 items-end gap-2">{[35,52,44,68,58,82,72,95].map((h,i)=><div key={i} className="flex-1 rounded-t bg-blue-200" style={{height:`${h}%`}}/> )}</div></div></div></div></div></section>
 <section id="businesses" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Designed by vertical</p><h2 className="mt-3 text-4xl font-black tracking-tight">The right experience for the work you actually do.</h2><p className="mt-4 leading-7 text-slate-600">You choose your organization type during setup. Sahel then keeps the relevant modules, language and workflow front and center.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{verticals.map(({icon:Icon,title,text,items})=><article key={title} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-100/50"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Icon/></div><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><div className="mt-6 space-y-3">{items.map(x=><div key={x} className="flex items-center gap-2 text-sm font-bold text-slate-700"><Check className="h-4 w-4 text-blue-600"/>{x}</div>)}</div></article>)}</div></section>
 <section id="features" className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">One calm system</p><h2 className="mt-3 text-4xl font-black tracking-tight">Everything important, without the clutter.</h2><p className="mt-4 leading-7 text-slate-300">Each workspace is focused. Shop owners do not need school modules, and school teams do not need retail screens.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text])=><div key={title} className="bg-slate-950 p-7"><Icon className="h-6 w-6 text-blue-300"/><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section>
 <section id="how" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-3">{[["01","Choose your workspace","Select Shop, School or Gym during account creation."],["02","Add your organization details","Name, phone, location and the details that make the workspace yours."],["03","Work in a focused dashboard","Your modules and navigation are tailored to the organization you selected."]].map(([n,t,x])=><div key={n} className="rounded-3xl border border-slate-200 p-7"><span className="text-sm font-black text-blue-600">{n}</span><h3 className="mt-8 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{x}</p></div>)}</div></section>
 <section id="faq" className="border-t border-slate-100 bg-slate-50"><div className="mx-auto max-w-4xl px-5 py-20 sm:px-8"><h2 className="text-4xl font-black tracking-tight">Questions, answered.</h2><div className="mt-8 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white">{[["Can I use Sahel for a school?","Yes. Choose School during signup and Sahel will present the school-focused workspace."],["Can I use it for a gym?","Yes. Gym accounts focus on members, check-ins, payments and staff."],["Can I change my organization type later?","The current system locks the type when the workspace is created so the dashboard remains consistent."],["What about other organizations?","Sahel is designed as a multi-vertical platform. More specialized workspaces can be added without changing the core experience."]].map(([q,a])=><details key={q} className="group p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-black">{q}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180"/></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{a}</p></details>)}</div></div></section>
 <section className="bg-blue-600"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-7 px-5 py-16 text-white sm:px-8 md:flex-row md:items-center"><div><p className="text-sm font-bold text-blue-100">Ready to build your workspace?</p><h2 className="mt-2 text-3xl font-black">Start with the tools your organization actually needs.</h2></div><Link to="/signup" className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-black text-blue-700">Get started <ArrowRight className="h-4 w-4"/></Link></div></section>
 <footer className="bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm sm:px-8 md:flex-row md:items-center md:justify-between"><img src={sahelLogo} className="h-7 brightness-0 invert" alt="Sahel"/><p>Business management software built for organizations in Somalia.</p><p>© 2026 Sahel. All rights reserved.</p></div></footer>
 </main>}
