import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Check, ChevronLeft, ChevronRight, Download, Dumbbell, GraduationCap, Menu, Package, ReceiptText, School, ShieldCheck, Store, Users, WalletCards, X, Zap } from "lucide-react";
import sahelLogo from "../assets/sahel_logo_english.svg";

const verticals = [
  { key: "school", icon: GraduationCap, title: "School Management", short: "Schools", color: "from-blue-600 to-indigo-700", image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80", text: "Admissions, students, teachers, classes, fees, exams and school records in one focused workspace.", items: ["Admissions & students", "Teachers & classes", "Fees & exams"] },
  { key: "shop", icon: Store, title: "Shop Management", short: "Shops", color: "from-emerald-500 to-teal-700", image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80", text: "Sales, inventory, receipts, customer credit, expenses and reports without spreadsheet clutter.", items: ["Sales & receipts", "Inventory", "Customer credit"] },
  { key: "gym", icon: Dumbbell, title: "Gym Management", short: "Gyms", color: "from-violet-600 to-purple-800", image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80", text: "Members, gender breakdowns, payments, staff and membership renewals in one simple system.", items: ["Members & profiles", "Payments & renewals", "Staff management"] },
];

const features = [
  [ReceiptText, "Sales & receipts", "Create clear receipts and keep daily records organized."],
  [Package, "Inventory", "Know what you have, what is moving and what needs attention."],
  [Users, "People management", "Students, customers, members and staff in the right workspace."],
  [WalletCards, "Payments", "Track payments, outstanding balances and recurring dues."],
  [BarChart3, "Reports", "Turn your daily records into information you can act on."],
  [ShieldCheck, "Secure workspace", "Keep your organization in one controlled, professional workspace."],
];

export default function LandingV2() {
  const [menu, setMenu] = useState(false);
  const [active, setActive] = useState(0);
  const [installEvent, setInstallEvent] = useState(null);
  const [installed, setInstalled] = useState(false);
  const current = verticals[active];

  useEffect(() => {
    const onPrompt = (e) => { e.preventDefault(); setInstallEvent(e); };
    const onInstalled = () => { setInstalled(true); setInstallEvent(null); };
    window.addEventListener("beforeinstallprompt", onPrompt);
    window.addEventListener("appinstalled", onInstalled);
    setInstalled(window.matchMedia?.("(display-mode: standalone)")?.matches || window.navigator.standalone === true);
    return () => { window.removeEventListener("beforeinstallprompt", onPrompt); window.removeEventListener("appinstalled", onInstalled); };
  }, []);

  useEffect(() => { const timer = setInterval(() => setActive((i) => (i + 1) % verticals.length), 5500); return () => clearInterval(timer); }, []);
  const progress = useMemo(() => `${((active + 1) / verticals.length) * 100}%`, [active]);

  async function installApp() {
    if (!installEvent) { document.getElementById("install-help")?.scrollIntoView({ behavior: "smooth" }); return; }
    installEvent.prompt();
    const result = await installEvent.userChoice;
    if (result.outcome === "accepted") setInstallEvent(null);
  }

  return <main className="min-h-screen overflow-x-hidden bg-white text-slate-950">
    <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/95 shadow-sm backdrop-blur-xl"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-6 px-4 sm:px-8">
      <Link to="/welcome" className="shrink-0"><img src={sahelLogo} className="h-12 w-auto sm:h-14" alt="Sahel" /></Link>
      <nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#businesses" className="hover:text-blue-600">Solutions</a><a href="#features" className="hover:text-blue-600">Features</a><a href="#install" className="hover:text-blue-600">Install</a><a href="#how" className="hover:text-blue-600">How it works</a></nav>
      <div className="hidden items-center gap-2 md:flex">{!installed && <button onClick={installApp} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm font-black text-blue-700 hover:bg-blue-100"><Download className="h-4 w-4"/> Install</button>}<Link to="/login" className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Log in</Link><Link to="/signup" className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white shadow-lg shadow-blue-200 hover:bg-blue-700">Get started</Link></div>
      <button className="rounded-xl p-2 md:hidden" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X/> : <Menu/>}</button>
    </div>{menu && <div className="border-t border-slate-100 bg-white p-5 md:hidden"><div className="grid gap-3 text-sm font-bold"><a href="#businesses" onClick={() => setMenu(false)}>Solutions</a><a href="#features" onClick={() => setMenu(false)}>Features</a><a href="#install" onClick={() => setMenu(false)}>Install Sahel</a><a href="#how" onClick={() => setMenu(false)}>How it works</a><Link to="/login">Log in</Link><Link to="/signup" className="rounded-xl bg-blue-600 px-4 py-3 text-center text-white">Get started</Link></div></div>}</header>

    <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-gradient-to-br from-blue-950 via-slate-950 to-indigo-950"/><div className="absolute -right-40 top-0 h-[500px] w-[500px] rounded-full bg-blue-500/20 blur-3xl"/><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-4 py-10 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-16">
      <div className="order-2 lg:order-1"><div className="inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-white/10 px-3 py-1.5 text-xs font-black text-blue-200"><Zap className="h-3.5 w-3.5"/> One platform. Many organizations.</div><h1 className="mt-5 max-w-2xl text-4xl font-black leading-[1.02] tracking-tight sm:text-6xl">Manage your <span className="text-blue-400">{current.short.toLowerCase()}</span> with Sahel.</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">{current.text}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-black text-white shadow-xl shadow-blue-900/40 hover:bg-blue-500">Start with Sahel <ArrowRight className="h-4 w-4"/></Link><button onClick={installApp} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/10 px-6 py-3.5 text-sm font-black text-white hover:bg-white/15"><Download className="h-4 w-4"/> Install Sahel</button></div><div className="mt-8 grid grid-cols-3 gap-2 sm:max-w-xl">{verticals.map((v, i) => { const Icon = v.icon; return <button key={v.key} onClick={() => setActive(i)} className={`rounded-2xl border p-3 text-left transition ${i === active ? "border-blue-400 bg-white/15" : "border-white/10 bg-white/5 hover:bg-white/10"}`}><Icon className="h-5 w-5"/><span className="mt-2 block text-xs font-black">{v.short}</span></button>; })}</div></div>
      <div className="order-1 lg:order-2"><div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-white/10 p-2 shadow-2xl backdrop-blur"><div className="relative h-[360px] overflow-hidden rounded-[1.5rem] sm:h-[470px]"><img key={current.key} src={current.image} alt={current.title} className="absolute inset-0 h-full w-full object-cover transition duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className={`mb-4 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${current.color}`}><current.icon className="h-6 w-6"/></div><p className="text-sm font-bold text-blue-200">Sahel workspace</p><h2 className="mt-1 text-3xl font-black">{current.title}</h2><div className="mt-5 flex flex-wrap gap-2">{current.items.map((x) => <span key={x} className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold backdrop-blur">{x}</span>)}</div></div><button onClick={() => setActive((active - 1 + verticals.length) % verticals.length)} className="absolute left-4 top-1/2 rounded-full border border-white/20 bg-black/30 p-2 backdrop-blur" aria-label="Previous"><ChevronLeft/></button><button onClick={() => setActive((active + 1) % verticals.length)} className="absolute right-4 top-1/2 rounded-full border border-white/20 bg-black/30 p-2 backdrop-blur" aria-label="Next"><ChevronRight/></button></div><div className="px-4 pb-3 pt-3"><div className="h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-400 transition-all duration-500" style={{ width: progress }}/></div></div></div></div>
    </div></section>

    <section id="businesses" className="mx-auto max-w-7xl px-4 py-20 sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Built for the way you work</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">School. Shop. Gym. One Sahel.</h2><p className="mt-4 text-base leading-7 text-slate-600">Your workspace changes around your organization. The landing page can highlight each solution without forcing everyone into the same experience.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{verticals.map((v, i) => { const Icon = v.icon; return <button key={v.key} onClick={() => setActive(i)} className={`group rounded-3xl border p-7 text-left transition duration-300 hover:-translate-y-2 hover:shadow-2xl ${i === active ? "border-blue-300 bg-blue-50/50 shadow-lg shadow-blue-100" : "border-slate-200 bg-white"}`}><div className="flex items-center justify-between"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${v.color} text-white`}><Icon/></span><ArrowRight className="h-5 w-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-600"/></div><h3 className="mt-6 text-xl font-black">{v.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{v.text}</p><div className="mt-5 space-y-2">{v.items.map(x => <div key={x} className="flex items-center gap-2 text-sm font-bold text-slate-700"><Check className="h-4 w-4 text-blue-600"/>{x}</div>)}</div></button>; })}</div></section>

    <section id="features" className="bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Everything important</p><h2 className="mt-3 text-4xl font-black tracking-tight">Less empty space. More useful information.</h2></div><p className="max-w-xl text-base leading-7 text-slate-600">Sahel brings the important work forward: admissions and school records, shop operations, gym memberships, payments, reports and more—based on the organization you use.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text]) => <article key={title} className="group rounded-3xl border border-slate-200 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600 transition group-hover:scale-110"><Icon/></div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="install" className="bg-blue-600 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-8 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-100">Install Sahel</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Use Sahel like an app on your phone or computer.</h2><p className="mt-4 max-w-2xl text-base leading-7 text-blue-100">On supported browsers, tap Install and Sahel can be added to your home screen or desktop. The same responsive web app works on laptop, desktop and phone without creating a separate experience.</p><button onClick={installApp} disabled={installed} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-black text-blue-700 shadow-xl disabled:opacity-70"><Download className="h-4 w-4"/>{installed ? "Sahel is installed" : "Install Sahel"}</button><p id="install-help" className="mt-4 text-xs text-blue-100">If your browser does not show the install prompt, use the browser menu and choose <strong>Install Sahel</strong> or <strong>Add to Home Screen</strong>.</p></div><div className="rounded-3xl border border-white/20 bg-white/10 p-6 backdrop-blur"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-2xl bg-white/10 p-5"><p className="text-xs font-bold text-blue-100">Phone</p><p className="mt-1 font-black">Home-screen app</p><p className="mt-2 text-sm text-blue-100">Open Sahel from your phone like a normal app.</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-xs font-bold text-blue-100">Desktop</p><p className="mt-1 font-black">Install on PC / laptop</p><p className="mt-2 text-sm text-blue-100">Install from a supported browser without changing the desktop layout.</p></div></div></div></div></section>

    <section id="how" className="mx-auto max-w-7xl px-4 py-20 sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Simple setup</p><h2 className="mt-3 text-4xl font-black">Choose your organization. Sahel does the rest.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["01","Choose your workspace","Select School Management, Shop Management or Gym Management during setup."],["02","Your workspace adapts","The relevant modules, navigation and terminology stay in front of you."],["03","Work anywhere","Use the same account on desktop, laptop or phone, and install Sahel when your browser supports it."]].map(([n,t,x]) => <div key={n} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><span className="text-sm font-black text-blue-600">{n}</span><h3 className="mt-7 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{x}</p></div>)}</div></section>

    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-16 text-center sm:px-8"><p className="text-sm font-bold text-blue-300">Sahel</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl font-black sm:text-5xl">One platform for the work that matters.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-400">From school admissions to shop sales to gym memberships, keep the important parts of your organization in one place.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-black text-white hover:bg-blue-500">Create your workspace <ArrowRight className="h-4 w-4"/></Link><button onClick={installApp} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 px-6 py-3.5 text-sm font-black hover:bg-white/10"><Download className="h-4 w-4"/> Install Sahel</button></div></div></section>

    <footer className="bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 border-t border-white/10 px-4 py-8 text-sm sm:px-8 md:flex-row md:items-center md:justify-between"><img src={sahelLogo} className="h-10 w-auto brightness-0 invert" alt="Sahel"/><p>Business management software built for organizations in Somalia.</p><p>© 2026 Sahel. All rights reserved.</p></div></footer>
  </main>;
}
