const T = {
  en: {
    "nav.features": "Features", "nav.how": "How it works", "nav.stories": "Stories",
    "nav.faq": "FAQ", "nav.whatsapp": "WhatsApp", "nav.login": "Login",
    "nav.register": "Register", "nav.registerSoon": "Registration coming soon!",
    "hero.eyebrow": "Sales & Inventory Tracker",
    "hero.headline": "Shop Management Software Somalia — Track Sales, Stock & Debts from Your Phone",
    "hero.sub": "Sahel is the leading shop management software Somalia businesses trust. It records every sale, alerts you when stock is low, and keeps a list of who owes you money. This shop management software Somalia works offline and speaks your language — Somali, English, and Arabic.",
    "hero.ctaPrimary": "WhatsApp us to start", "hero.ctaSecondary": "How it works",
    "hero.trust": "Used by 2,000+ shop owners", "hero.chartTitle": "Weekly sales — tap a day",
    "hero.topProduct": "TOP PRODUCT", "hero.revenue": "WEEK TOTAL", "hero.growth": "VS LAST WEEK",
    "trust.bar": "Used by these businesses",
    "why.eyebrow": "Built for Somalia", "why.title": "Why Sahel is the #1 Shop Management Software Somalia",
    "why.body": "Sahel is shop management software Somalia businesses rely on daily. Shop owners across Mogadishu, Hargeisa, and Kismayo use this shop management software Somalia to track inventory, record sales, and manage customer credit — without needing a steady internet connection. Unlike generic accounting apps, this shop management software Somalia speaks Somali, works through intermittent connectivity, and understands how Somali businesses actually operate. If you're searching for shop management software in Somalia, Sahel was built exactly for you.",
    "features.eyebrow": "What Sahel does", "features.title": "Six Things This Shop Management Software Somalia Handles",
    "features.sub": "Sahel is shop management software Somalia shop owners use daily. These are the tasks you currently do on paper or in your head — this shop management software Somalia does them automatically.",
    "f1t": "Records your stock", "f1b": "Sahel counts what comes in and what goes out. When an item is running low, it sends you an alert before you sell out.",
    "f2t": "Records every sale", "f2b": "Each time you sell something, tap it in Sahel. It adds up your daily, weekly, and monthly revenue automatically.",
    "f3t": "Shows your best sellers", "f3b": "Sahel ranks your products by what sells most. You see which items make money and which ones don't move.",
    "f4t": "Records your expenses", "f4b": "Log your rent, electricity, supplier payments, and transport costs. Sahel subtracts them from your revenue so you see real profit.",
    "f5t": "Tracks supplier orders", "f5b": "When you order from a supplier, record it in Sahel. It tracks what you ordered, when it's due, and whether it arrived.",
    "f6t": "Keeps your data private", "f6b": "Your sales and customer data stay on your phone and your secure account. Nobody else can see it.",
    "how.eyebrow": "Get started", "how.title": "Three Steps to Start Using This Shop Management Software Somalia",
    "how.sub": "No setup wizard. No training videos. If you've ever sent a WhatsApp message, you can use this shop management software Somalia right now.",
    "s1t": "Enter your name and phone number", "s1b": "That's all Sahel asks for. No email, no password to remember.",
    "s2t": "Type a product name and its price", "s2b": "Add one product, sell it. Add another one later. You don't need to set up everything at once.",
    "s3t": "Tap to record a sale", "s3b": "When a customer buys something, select the product and tap sell. Sahel updates your stock and revenue automatically.",
    "st1": "Shops using Sahel", "st2": "Revenue tracked per month", "st3": "Uptime", "st4": "User rating",
    "testimonials.eyebrow": "From our users", "testimonials.title": "What Business Owners Say About This Shop Management Software Somalia",
    "t1q": '"We were losing money because we forgot who paid and who didn\'t across three locations. Sahel fixed that. Now every sale and every debt is recorded. We recovered $1,800 in the first month."',
    "t2q": '"We have 350 appliance models. Counting stock on paper was impossible. Sahel tracks it all. Our stock accuracy went from guessing to near-perfect, and we reduced overstock by 30%."',
    "t3q": '"Fashion inventory changes every season. Before Sahel, I ordered based on gut feeling. Now I order based on what actually sells. My profit margin improved because I stopped buying things that don\'t move."',
    "faq.eyebrow": "Common questions", "faq.title": "Answers About This Shop Management Software Somalia",
    "fq1": "Is Sahel free?", "fa1": "Yes. Recording sales, tracking stock, and listing customer debts is free and will stay free.",
    "fq2": "Does it work without internet?", "fa2": "Yes. Every sale and stock update is saved on your phone first. When your phone connects to the internet again, it syncs automatically.",
    "fq3": "Can my employees use it?", "fa3": "Yes. You create accounts for your staff. They can record sales, but only you see the full financial picture.",
    "fq4": "Is my data safe?", "fa4": "Your data is encrypted and stored securely. Only you can access your business records.",
    "cta.eyebrow": "Free to start",
    "cta.title": "Stop Losing Money — Get Shop Management Software Somalia Today",
    "cta.sub": "WhatsApp us now on +252 624 407 283 and we'll set you up with shop management software Somalia in minutes.",
    "cta.button": "WhatsApp us now", "cta.secondary": "See features",
    "footer.desc": "Sahel is shop management software Somalia businesses trust. It records your sales, manages your stock, and tracks who owes you money — from your phone, in Somali, English, and Arabic.",
    "footer.product": "Product", "footer.feat": "Features", "footer.how": "How it works",
    "footer.support": "Support", "footer.help": "FAQ", "footer.contact": "WhatsApp Us",
    "footer.tagline": "Shop management software Somalia — Built for shop owners, by shop owners.",
    "chart.sales": "SALES", "chart.transactions": "TRANSACTIONS",
    "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  },
  so: {
    "nav.features": "Muuqaal", "nav.how": "Sida ay u shaqeyso", "nav.stories": "Sheekooyin",
    "nav.faq": "Su'aalo", "nav.whatsapp": "WhatsApp", "nav.login": "Gal",
    "nav.register": "Diiwaan geli", "nav.registerSoon": "Diiwaan gelinta soon!",
    "hero.eyebrow": "La soco iibka iyo bakhaarka",
    "hero.headline": "Sahel — Software-ka Maamulka Dukaanka ee Soomaaliya. La soco iibkaaga, bakhaarka, iyo deynta macaamiisha taleefankaaga.",
    "hero.sub": "Sahel waxay diiwaan gelisaa iib kasta, waxay ku dhawaaqdaa marka alaabtu yartahay, waxayna kaydisaa liiska kuwa lacag kuu leh. Waxay shaqeynaysaa internet la'aan oo afkaaga waa Soomaali, Ingiriisi iyo Carabi.",
    "hero.ctaPrimary": "WhatsApp nala soo xiriir", "hero.ctaSecondary": "Sida ay u shaqeyso",
    "hero.trust": "2,000+ oo dukaan oo isticmaala Sahel", "hero.chartTitle": "Iibka toddobaadkan — taabo maalinta",
    "hero.topProduct": "ALAABTA UGU IIBKA BADAN", "hero.revenue": "WADARTA TODDOBAADKA", "hero.growth": "TODDOBAADKA HORE",
    "trust.bar": "Dukaanoyin kuwaan isticmaala",
    "why.eyebrow": "Loo dhisay Soomaaliya", "why.title": "Software-ka Maamulka Dukaanka ee Loo Dhisay Soomaaliya",
    "why.body": "Sahel waa software maamul dukaan oo si gaar ah loogu dhisay Soomaaliya. Maalin kasta, milkiilayaal dukaan ah oo ku nool Muqdisho, Hargeysa, iyo Kismaayo ayaa isticmaala Sahel si ay ula socdaan bakhaarkooda, u diiwaan geliyaan iibkooda, oo ay u maamulaan deynta macaamiisha — iyada oo aan loo baahnayn internet joogto ah. Marka loo eego apps-ka caadiga ah ee dalal kale loo sameeyay, Sahel wuxuu ku hadlaa Soomaali, wuxuuna la shaqeeyaa internet aan joogto ahayn, wuxuuna fahansan yahay sida ganacsiga Soomaalidu dhab ahaantii u shaqeeyo.",
    "features.eyebrow": "Waxaa Sahel sameeyaa", "features.title": "Lixdar oo Sahel kuu qabtaa",
    "features.sub": "Sahel waa software maamul dukaan oo loogu dhisay Soomaaliya. Waa shaqooyin hadda warqad ama maskaxda ku sameeyso. Sahel waxay sameeyaa si otomaatig ah, sax ah, oo waad la socdi karo taleefankaaga wakhti kasta.",
    "f1t": "Waxay kaydisaa bakhaarka", "f1b": "Sahel waxay tirinaysaa waxa soo gelayaa iyo waxa baxaysaa. Marka alaabtu yartahay, waxay ku dhawaaqdaa inta aysan dhammaan.",
    "f2t": "Waxay diiwaan gelisaa iib kasta", "f2b": "Marka iibto dhacdo, taabo Sahel. Waxay isku daraysaa dakhligaaga maalinlaha, toddobaadlaha, iyo bisha si otomaatig ah.",
    "f3t": "Waxay muuqataa alaabta ugu iibsata", "f3b": "Sahel waxay isla soo qortaa alaabta sida iibka ugu badan. Waxaad arki doontaa waxa lacag geysata iyo waxa aan la iibin.",
    "f4t": "Waxay kaydisaa kharashka", "f4b": "Diiwaan geli kirada, korontada, lacag bixinta supplier-ka, iyo kharashga gaadinka. Sahel waxay ka saartaa dakhligaaga si aad u aragto faa'idada dhabta ah.",
    "f5t": "Waxay la socotaa dalabka supplier-ka", "f5b": "Marka aad supplier-ka ka dalbayso, diiwaan geli Sahel. Waxay la socotaa waxa dalbayso, waqtiga, iyo inay yimaaddo.",
    "f6t": "Waxay xifdisaa xogtaada", "f6b": "Xogta iibkaaga iyo macaamiishaaga waxay ku sugan tahay taleefankaaga iyo account-kaaga ammaan ka ah. Qofna ma arki karo.",
    "how.eyebrow": "Bilaow", "how.title": "Sadar saddex ah, daqiiqo shan, waad shaqeynaysaa",
    "how.sub": "Wax setup ah, wax video barasho ah. Hadii aad weli WhatsApp diri karto, Sahel waad isticmaali kartaa hadda.",
    "s1t": "Geli magacaaga iyo lambaraga taleefanka", "s1b": "Sahel waxay weyddiisaa oo keliya. Iimayl, furasho, tixraac xumaan maaha.",
    "s2t": "Qor magaca alaabta iyo qiimaha", "s2b": "Kudar alaab halmar, iibi. Kadib kudar mid kale. Wax kasta waa inaad iskugu darin waqtigaas.",
    "s3t": "Taabo si aad u diiwaan geliso iibka", "s3b": "Marka macmiil iibo, dooro alaabta oo taabo iibi. Sahel waxay cusbooneysiiyaa bakhaarka iyo dakhliga si otomaatig ah.",
    "st1": "Dukaan isticmaala Sahel", "st2": "Dakhli la soco bishan", "st3": "Waqtiga shaqeyn", "st4": "Qiime muuqalka",
    "testimonials.eyebrow": "Ka isticmaalayaashayada", "testimonials.title": "Waxay ganacsatada sheegaan Sahel",
    "t1q": '"Waxaan la waashay lacag ceeb ah sababtoo ah waxaan isdilay mid bixiyay iyo midna aan bixin saddex meelood. Sahel waxay xallisey. Hadda iib kasta iyo deyn kasta waa la diiwaan geliyaa. Bishii ugu horeysay waxaan ka soo celiyay $1,800."',
    "t2q": '"Waxaan haynaa 350 nooc oo qalab guriga ah. Tirinta bakhaarka warqad ahaanna ayay ku dhacday Sahel. Saxda bakhaarka waxay ka baxday dhamaan oo waa yaraaday 30% kharashda ku waynaatay."',
    "t3q": '"Dhar business-ka waxay badaltaa jiilaalka. Hore Sahel, waxaan order gelin jiray rajo. Hadda waxaan order geliyaa sida waxa dhabta ah loo iibiyo. Faaiidadaaday waaa korodhay."',
    "faq.eyebrow": "Su'aalo caadi ah", "faq.title": "Jawaabo su'aalooyin oo nala weydiiyay",
    "fq1": "Sahel ma bilaash bay ahayd?", "fa1": "Haa. Diiwaanka iibka, la socodka bakhaarka, iyo liiska deynta macaamiisha waa bilaash.",
    "fq2": "Internet la'aan ma shaqeyn?", "fa2": "Haa. Iib kasta iyo cusboonayn bakhaarka waxay kaydisaa taleefankaaga horta. Marka internet ku soo baxdo, waxay si otomaatig ah u midowdaa.",
    "fq3": "Shaqaalaydu isticmaali karaa?", "fa3": "Haa. Waxaad sameysaa account shaqaale kasta. Waxay diiwaan geli karaan iib, oo kaliya aad oo ahaan muhiimka ah ayaad arki doontaa.",
    "fq4": "Xogtayda ma ammaan bay ahayd?", "fa4": "Xogtaada waa la xifdiyaa si ammaan ah. Aad oo kaliya ayaa arki karta xogtaaga ganacsiga.",
    "cta.eyebrow": "Bilaash inaad bilaabto",
    "cta.title": "Jooji inaad lacag la waasho deyno daalan iyo daaweyn xumaan.",
    "cta.sub": "WhatsApp nala soo xiriir hadda +252 624 407 283 oo waan ku diyaarinnaa daqiiqado.",
    "cta.button": "WhatsApp nala soo xiriir", "cta.secondary": "Eeg muuqaalada",
    "footer.desc": "Sahel waa software maamul dukaan oo loogu dhisay Soomaaliya. Wuxuu diiwaan gelisaa iibkaaga, maamulaa bakhaarka, oo la socdaa kuwa lacag kuu leh — taleefankaaga, Soomaali, Ingiriisi, iyo Carabi.",
    "footer.product": "Badeecad", "footer.feat": "Muuqaal", "footer.how": "Sida ay u shaqeyso",
    "footer.support": "Taageero", "footer.help": "Su'aalo", "footer.contact": "WhatsApp Nala Xiriir",
    "footer.tagline": "Laga dhisay ganacsato, oo ganacsato.",
    "chart.sales": "IIBKA", "chart.transactions": "DHAQDHAQAAQ",
    "days": ["Isniin", "Talaada", "Arbaco", "Khamiis", "Jimco", "Sabti", "Axad"],
  },
  ar: {
    "nav.features": "المميزات", "nav.how": "كيف يعمل", "nav.stories": "قصص",
    "nav.faq": "أسئلة", "nav.whatsapp": "واتساب", "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب", "nav.registerSoon": "التسجيل قريباً!",
    "hero.eyebrow": "تتبع المبيعات والمخزون",
    "hero.headline": "ساهل — برنامج إدارة المتاجر في الصومال. نسجّل مبيعاتك ومخزونك وديون عملائك من هاتفك.",
    "hero.sub": "ساهل يسجّل كل عملية بيع، ينبهك عندما ينخفض المخزون، ويحتفظ بقائمة بمن لك عنده دين. يعمل بدون إنترنت ويتكلم بلغتك — الصومالية والإنجليزية والعربية.",
    "hero.ctaPrimary": "تواصل معنا عبر واتساب", "hero.ctaSecondary": "كيف يعمل",
    "hero.trust": "يستخدمه أكثر من 2,000 صاحب متجر", "hero.chartTitle": "مبيعات الأسبوع — اضغط على يوم",
    "hero.topProduct": "المنتج الأكثر مبيعاً", "hero.revenue": "إجمالي الأسبوع", "hero.growth": "مقارنة بالأسبوع السابق",
    "trust.bar": "يستخدمه هذه المتاجر",
    "why.eyebrow": "مصمم من أجل الصومال", "why.title": "برنامج إدارة المتاجر المصمم للصومال",
    "why.body": "ساهل هو برنامج إدارة متاجر مصمم خصيصاً للصومال. يومياً، يستخدم أصحاب المتاجر في مقديشو وهرجيسا وكيسمايو تطبيق ساهل لتتبع المخزون وتسجيل المبيعات وإدارة ديون العملاء — دون الحاجة لاتصال إنترنت دائم. على عكس تطبيقات المحاسبة العامة المصممة لأسواق أخرى، يتحدث ساهل الصومالية، ويعمل مع الاتصال المتقطع، ويفهم كيف تعمل الأعمال الصومالية فعلياً.",
    "features.eyebrow": "ماذا يفعل ساهل", "features.title": "ستة أشياء يتعامل معها ساهل",
    "features.sub": "ساهل هو برنامج إدارة متاجر مصمم للصومال. هذه المهام التي تقوم بها حالياً على الورق أو في رأسك. ساهل يقوم بها تلقائياً ويمكنك مراجعتها أي وقت من هاتفك.",
    "f1t": "يسجّل مخزونك", "f1b": "ساهل يحسب ما يدخل وما يخرج. عندما ينخفض منتج، يرسل لك تنبيهاً قبل أن تنفذ الكمية.",
    "f2t": "يسجّل كل عملية بيع", "f2b": "كلما بعت شيئاً، اضغط عليه في ساهل. يجمع إيراداتك اليومية والأسبوعية والشهرية تلقائياً.",
    "f3t": "يُظهر أكثر المنتجات مبيعاً", "f3b": "ساهل يرتب منتجاتك حسب الأكثر مبيعاً. ترى أي المنتجات تجلب المال وأيها لا تتحرك.",
    "f4t": "يسجّل مصروفاتك", "f4b": "سجّل الإيجار والكهرباء ودفعات الموردين وتكاليف النقل. ساهل يطرحها من إيراداتك فترى الربح الحقيقي.",
    "f5t": "يتتبع طلبات الموردين", "f5b": "عندما تطلب من مورد، سجّله في ساهل. يتتبع ما طلبته وموعد الاستلام وهل وصل.",
    "f6t": "يحافظ على خصوصية بياناتك", "f6b": "بيانات مبيعاتك وعملائك تبقى على هاتفك وحسابك الآمن. لا أحد غيرك يمكنه رؤيتها.",
    "how.eyebrow": "ابدأ الآن", "how.title": "ثلاث خطوات، خمس دقائق، أنت تعمل",
    "how.sub": "بدون معالج إعداد. بدون فيديوهات تدريب. إذا أرسلت رسالة واتساب من قبل، يمكنك استخدام ساهل الآن.",
    "s1t": "أدخل اسمك ورقم هاتفك", "s1b": "هذا كل ما يطلبه ساهل. بدون بريد إلكتروني، بدون كلمة مرور.",
    "s2t": "اكتب اسم المنتج وسعره", "s2b": "أضف منتجاً واحداً وابدأ البيع. لا تحتاج لإعداد كل شيء مرة واحدة.",
    "s3t": "اضغط لتسجيل عملية بيع", "s3b": "عندما يشتري عميل شيئاً، اختر المنتج واضغط بيع. ساهل يحدّث مخزونك وإيراداتك تلقائياً.",
    "st1": "متجر يستخدم ساهل", "st2": "إيرادات متتبعة شهرياً", "st3": "وقت التشغيل", "st4": "تقييم المستخدمين",
    "testimonials.eyebrow": "من مستخدمينا", "testimonials.title": "ماذا يقول أصحاب المتاجر عن ساهل",
    "t1q": '"كنا نخسر المال لأننا كنا ننسى من دفع ومن لم يدفع عبر ثلاثة فروع. ساهل حلّ هذه المشكلة. الآن كل عملية بيع وكل دين مسجّل. استرددنا 1,800 دولار في الشهر الأول."',
    "t2q": '"لدينا 350 موديل جهاز منزلي. عد المخزون على الورق كان مستحيلاً. ساهل يتتبع كل شيء. دقة المخزون انتقلت من التخمين إلى شبه الكمال، وقللنا المخزون الزائد بنسبة 30%."',
    "t3q": '"مخزون الأزياء يتغير كل موسم. قبل ساهل، كنت أطلب بناءً على الحدس. الآن أطلب بناءً على ما يباع فعلاً. تحسنت هامش الربح لأنني توقفت عن شراء الأشياء التي لا تتحرك."',
    "faq.eyebrow": "أسئلة شائعة", "faq.title": "إجابات على الأسئلة التي يطرحها الناس علينا",
    "fq1": "هل ساهل مجاني؟", "fa1": "نعم. تسجيل المبيعات وتتبع المخزون وإعداد قائمة ديون العملاء مجاني وسيبقى مجانياً.",
    "fq2": "هل يعمل بدون إنترنت؟", "fa2": "نعم. كل عملية بيع وتحديث المخزون يتم حفظه على هاتفك أولاً. عندما يتصل هاتفك بالإنترنت مرة أخرى، يتم المزامنة تلقائياً.",
    "fq3": "هل يمكن لموظفي استخدامها؟", "fa3": "نعم. تقوم بإنشاء حسابات لموظفيك. يمكنهم تسجيل المبيعات، ولكن أنت فقط ترى الصورة المالية الكاملة.",
    "fq4": "هل بياناتي آمنة؟", "fa4": "بياناتك مشفرة ومخزنة بشكل آمن. أنت فقط يمكنك الوصول إلى سجلات عملك.",
    "cta.eyebrow": "مجاني للبدء",
    "cta.title": "توقف عن خسارة المال بسبب الديون المنسية والسجلات الفوضوية.",
    "cta.sub": "تواصل معنا عبر واتساب الآن على +252 624 407 283 وسنقوم بإعدادك في دقائق.",
    "cta.button": "تواصل معنا عبر واتساب الآن", "cta.secondary": "شاهد المميزات",
    "footer.desc": "ساهل هو برنامج إدارة متاجر مصمم للصومال. يسجّل مبيعاتك، يدير مخزونك، ويتتبع من لك عنده دين — من هاتفك، بالصومالية والإنجليزية والعربية.",
    "footer.product": "المنتج", "footer.feat": "المميزات", "footer.how": "كيف يعمل",
    "footer.support": "الدعم", "footer.help": "الأسئلة الشائعة", "footer.contact": "تواصل معنا عبر واتساب",
    "footer.tagline": "صُنع لأصحاب المتاجر، من قبل أصحاب المتاجر.",
    "chart.sales": "المبيعات", "chart.transactions": "المعاملات",
    "days": ["الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"],
  },
};
