const T = {
  en: {
    "nav.features": "Features", "nav.how": "How it works", "nav.stories": "Stories",
    "nav.faq": "FAQ", "nav.whatsapp": "WhatsApp", "nav.login": "Login",
    "nav.register": "Register", "nav.registerSoon": "Registration coming soon!",
    "hero.eyebrow": "Sales & Inventory Tracker",
    "hero.headline": "Shop Management Software Somalia — Track Sales, Stock & Debts from Your Phone",
    "hero.sub": "Sahel is the leading shop management software Somalia businesses trust. It records every sale, alerts you when stock is low, and keeps a list of who owes you money. This shop management software Somalia works offline and speaks your language — Somali, English, and Arabic.",
    "hero.ctaPrimary": "WhatsApp us to start", "hero.ctaSecondary": "How it works",
    "hero.trust": "Used by 2,000+ shop owners", "hero.chartTitle": "Weekly sales — tap a day",
    "hero.topProduct": "TOP PRODUCT", "hero.revenue": "WEEK TOTAL", "hero.growth": "VS LAST WEEK",
    "trust.bar": "Used by these businesses",
    "why.eyebrow": "Built for Somalia", "why.title": "Why Sahel is the #1 Shop Management Software Somalia",
    "why.body": "Sahel is shop management software Somalia businesses rely on daily. Shop owners across Mogadishu, Hargeisa, and Kismayo use this shop management software Somalia to track inventory, record sales, and manage customer credit — without needing a steady internet connection. Unlike generic accounting apps, this shop management software Somalia speaks Somali, works through intermittent connectivity, and understands how Somali businesses actually operate. If you're searching for shop management software in Somalia, Sahel was built exactly for you.",
    "features.eyebrow": "What Sahel does", "features.title": "Six Things This Shop Management Software Somalia Handles",
    "features.sub": "Sahel is shop management software Somalia shop owners use daily. These are the tasks you currently do on paper or in your head — this shop management software Somalia does them automatically.",
    "f1t": "Records your stock", "f1b": "Sahel counts what comes in and what goes out. When an item is running low, it sends you an alert before you sell out. This shop management software Somalia feature saves you from stockouts.",
    "f2t": "Records every sale", "f2b": "Each time you sell something, tap it in Sahel. It adds up your daily, weekly, and monthly revenue automatically. Shop management software Somalia made simple.",
    "f3t": "Shows your best sellers", "f3b": "Sahel ranks your products by what sells most. You see which items make money and which ones don't move. Essential shop management software Somalia analytics.",
    "f4t": "Records your expenses", "f4b": "Log your rent, electricity, supplier payments, and transport costs. Sahel subtracts them from your revenue so you see real profit. Complete shop management software Somalia solution.",
    "f5t": "Tracks supplier orders", "f5b": "When you order from a supplier, record it in Sahel. It tracks what you ordered, when it's due, and whether it arrived. Shop management software Somalia suppliers trust.",
    "f6t": "Keeps your data private", "f6b": "Your sales and customer data stay on your phone and your secure account. Nobody else can see it. Secure shop management software Somalia businesses need.",
    "how.eyebrow": "Get started", "how.title": "Three Steps to Start Using This Shop Management Software Somalia",
    "how.sub": "No setup wizard. No training videos. If you've ever sent a WhatsApp message, you can use this shop management software Somalia right now.",
    "s1t": "Enter your name and phone number", "s1b": "That's all Sahel asks for. No email, no password to remember. Start using shop management software Somalia in seconds.",
    "s2t": "Type a product name and its price", "s2b": "Add one product, sell it. Add another one later. You don't need to set up everything at once with this shop management software Somalia.",
    "s3t": "Tap to record a sale", "s3b": "When a customer buys something, select the product and tap sell. Sahel updates your stock and revenue automatically. Shop management software Somalia at its simplest.",
    "st1": "Shops using Sahel", "st2": "Revenue tracked per month", "st3": "Uptime", "st4": "User rating",
    "testimonials.eyebrow": "From our users", "testimonials.title": "What Business Owners Say About This Shop Management Software Somalia",
    "t1q": '"We were losing money because we forgot who paid and who didn\'t across three locations. This shop management software Somalia fixed that. Now every sale and every debt is recorded. We recovered $1,800 in the first month."',
    "t2q": '"We have 350 appliance models. Counting stock on paper was impossible. This shop management software Somalia tracks it all. Our stock accuracy went from guessing to near-perfect, and we reduced overstock by 30%."',
    "t3q": '"Fashion inventory changes every season. Before this shop management software Somalia, I ordered based on gut feeling. Now I order based on what actually sells. My profit margin improved because I stopped buying things that don\'t move."',
    "faq.eyebrow": "Common questions", "faq.title": "Answers About This Shop Management Software Somalia",
    "fq1": "Is Sahel shop management software Somalia free?", "fa1": "Yes. Recording sales, tracking stock, and listing customer debts is free and will stay free. This shop management software Somalia core features are completely free.",
    "fq2": "Does this shop management software Somalia work without internet?", "fa2": "Yes. Every sale and stock update is saved on your phone first. When your phone connects to the internet again, it syncs automatically. Shop management software Somalia designed for connectivity challenges.",
    "fq3": "Can my employees use this shop management software Somalia?", "fa3": "Yes. You create accounts for your staff. They can record sales, but only you see the full financial picture. Shop management software Somalia with proper access control.",
    "fq4": "Is my data safe with this shop management software Somalia?", "fa4": "Your data is encrypted and stored securely. Only you can access your business records. Shop management software Somalia with enterprise-grade security.",
    "cta.eyebrow": "Free to start",
    "cta.title": "Stop Losing Money — Get Shop Management Software Somalia Today",
    "cta.sub": "WhatsApp us now on +252 624 407 283 and we'll set you up with shop management software Somalia in minutes.",
    "cta.button": "WhatsApp us now", "cta.secondary": "See features",
    "footer.desc": "Sahel is shop management software Somalia businesses trust. It records your sales, manages your stock, and tracks who owes you money — from your phone, in Somali, English, and Arabic. The premier shop management software Somalia solution.",
    "footer.product": "Product", "footer.feat": "Features", "footer.how": "How it works",
    "footer.support": "Support", "footer.help": "FAQ", "footer.contact": "WhatsApp Us",
    "footer.tagline": "Shop management software Somalia — Built for shop owners, by shop owners.",
    "chart.sales": "SALES", "chart.transactions": "TRANSACTIONS",
    "days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  },
  // Keep so and ar translations the same for now
  so: { /* ... keep existing ... */ },
  ar: { /* ... keep existing ... */ },
};
