import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Check, ChevronDown, Download, Dumbbell, GraduationCap, Menu, Package, ReceiptText, ShieldCheck, Store, Users, WalletCards, X } from "lucide-react";
import sahelLogo from "../assets/sahel_logo_english.svg";

const businesses=[
 {icon:Store,title:"Retail & Shops",text:"Sales, inventory, customer credit, expenses and receipts in one place.",items:["Sales & receipts","Inventory","Customer credit"]},
 {icon:GraduationCap,title:"School Management",text:"Admissions, students, teachers, classes, fees, exams and school records.",items:["Admissions & students","Classes & teachers","Fees & exams"]},
 {icon:Dumbbell,title:"Gym Management",text:"Members, payments, renewals and staff organized without spreadsheets.",items:["Members","Payments & renewals","Staff"]}
];
const features=[[ReceiptText,"Sales & receipts","Create clear receipts and keep a reliable daily sales history."],[Package,"Inventory","See stock levels, sales movement and items that need attention."],[Users,"Customers & members","Keep important people, balances and activity organized."],[WalletCards,"Payments & fees","Track payments, outstanding balances and recurring dues."],[BarChart3,"Reports","Turn daily records into simple information you can act on."],[ShieldCheck,"Secure workspace","Keep your organization in one controlled, professional workspace."]];
const points=[38,52,46,67,59,78,70,92,84,98];

export default function LandingProfessional(){
 const [menu,setMenu]=useState(false); const [installEvent,setInstallEvent]=useState(null); const [view,setView]=useState("overview");
 useEffect(()=>{const h=e=>{e.preventDefault();setInstallEvent(e)};window.addEventListener("beforeinstallprompt",h);return()=>window.removeEventListener("beforeinstallprompt",h)},[]);
 async function install(){if(!installEvent){document.getElementById("install-help")?.scrollIntoView({behavior:"smooth"});return}installEvent.prompt();const r=await installEvent.userChoice;if(r.outcome==="accepted")setInstallEvent(null)}
 return <main className="min-h-screen bg-white text-slate-950">
  <header className="sticky top-0 z-40 border-b border-slate-100 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between px-4 sm:px-8"><Link to="/welcome"><img src={sahelLogo} className="h-9 w-auto sm:h-10" alt="Sahel"/></Link><nav className="hidden items-center gap-8 text-sm font-bold text-slate-600 md:flex"><a href="#features">Features</a><a href="#businesses">Businesses</a><a href="#how">How it works</a><a href="#about">Get to know us</a></nav><div className="hidden items-center gap-2 sm:flex"><button onClick={install} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><Download className="mr-1 inline h-4 w-4"/>Install</button><Link to="/login" className="rounded-xl px-3 py-2 text-sm font-bold">Log in</Link><Link to="/signup" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white shadow-lg shadow-blue-200">Get started</Link></div><button className="rounded-xl p-2 sm:hidden" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="border-t border-slate-100 bg-white p-4 sm:hidden"><div className="grid gap-2 text-sm font-bold"><a className="rounded-xl px-3 py-3" href="#features">Features</a><a className="rounded-xl px-3 py-3" href="#businesses">Businesses</a><a className="rounded-xl px-3 py-3" href="#about">Get to know us</a><button onClick={install} className="rounded-xl border px-3 py-3 text-left">Install Sahel</button><Link className="px-3 py-3" to="/login">Log in</Link><Link className="rounded-xl bg-blue-600 px-4 py-3 text-center text-white" to="/signup">Get started</Link></div></div>}</header>
  <section className="relative overflow-hidden bg-[#f7f9fd]"><div className="absolute -left-40 top-0 h-80 w-80 rounded-full bg-blue-200/35 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-12 sm:px-8 sm:py-20 lg:grid-cols-[1fr_.9fr] lg:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-black text-blue-700 shadow-sm"><span className="h-2 w-2 rounded-full bg-blue-600"/> Business management for growing organizations</div><h1 className="mt-5 text-[2.7rem] font-black leading-[1.02] tracking-tight sm:text-6xl">One platform.<br/><span className="text-blue-600">Built around your work.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">Sahel brings the right tools to shops, schools and gyms—without forcing every organization into the same dashboard.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-black text-white shadow-xl shadow-blue-200">Create your workspace <ArrowRight className="h-4 w-4"/></Link><a href="#businesses" className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold">See what Sahel supports</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-slate-500"><span><Check className="mr-1 inline h-4 w-4 text-blue-600"/>Mobile ready</span><span><Check className="mr-1 inline h-4 w-4 text-blue-600"/>English & Somali</span><span><Check className="mr-1 inline h-4 w-4 text-blue-600"/>One organized workspace</span></div></div>
   <div className="rounded-[1.75rem] border border-slate-200 bg-white p-3 shadow-[0_25px_70px_rgba(15,23,42,.12)] sm:p-5"><div className="rounded-2xl bg-slate-50 p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Sahel • Shop overview</p><p className="mt-1 text-lg font-black">Today at a glance</p></div><div className="rounded-xl bg-blue-600 p-2 text-white"><BarChart3 className="h-5 w-5"/></div></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl border bg-white p-2.5"><p className="text-[9px] text-slate-400">Sales</p><p className="font-black">$1,840</p></div><div className="rounded-xl border bg-white p-2.5"><p className="text-[9px] text-slate-400">Stock</p><p className="font-black">$12,480</p></div><div className="rounded-xl border bg-white p-2.5"><p className="text-[9px] text-slate-400">Money due</p><p className="font-black">$2,160</p></div></div><div className="mt-3 rounded-xl border bg-white p-3"><div className="flex justify-between"><p className="text-xs font-bold text-slate-500">Sales performance</p><span className="text-xs font-black text-emerald-600">+12.4%</span></div><svg viewBox="0 0 500 120" preserveAspectRatio="none" className="mt-3 h-28 w-full"><polyline points={points.map((v,i)=>`${(i/(points.length-1))*500},${115-v}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="4" className="text-blue-600" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="flex justify-between text-[9px] font-bold text-slate-400"><span>Mon</span><span>Wed</span><span>Fri</span><span>Sun</span></div></div><div className="mt-3 rounded-xl border bg-white p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-500">{view==="inventory"?"Inventory table":"Inventory movement"}</p><button onClick={()=>setView(view==="inventory"?"overview":"inventory")} className="text-[11px] font-black text-blue-600">{view==="inventory"?"Overview":"View stock"}</button></div>{view==="inventory"?<table className="mt-2 w-full text-left text-[10px]"><thead className="text-slate-400"><tr><th className="py-2">Item</th><th>Qty</th><th>Status</th></tr></thead><tbody>{[["Rice 25kg","42","In stock"],["Cooking Oil","18","Low stock"],["Sugar 10kg","31","In stock"]].map(r=><tr key={r[0]} className="border-t"><td className="py-2 font-bold">{r[0]}</td><td>{r[1]}</td><td className={r[2]==="Low stock"?"font-bold text-amber-600":"font-bold text-emerald-600"}>{r[2]}</td></tr>)}</tbody></table>:<div className="mt-3 flex h-14 items-end gap-1.5">{[42,58,50,70,61,80,67,90].map((h,i)=><div key={i} className="flex-1 rounded-t bg-blue-200" style={{height:`${h/1.5}px`}}/>)}</div>}</div></div></div>
  </div></section>
  <section id="businesses" className="mx-auto max-w-7xl px-4 py-16 sm:px-8 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Designed by vertical</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">The right experience for the work you actually do.</h2><p className="mt-4 leading-7 text-slate-600">Choose your organization type during setup. Sahel keeps the relevant modules and workflow front and center.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{businesses.map(({icon:Icon,title,text,items})=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Icon/></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><div className="mt-5 space-y-2">{items.map(x=><div key={x} className="text-sm font-bold text-slate-700"><Check className="mr-2 inline h-4 w-4 text-blue-600"/>{x}</div>)}</div></article>)}</div></section>
  <section id="features" className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-8 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">One calm system</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Everything important, without the clutter.</h2><p className="mt-4 leading-7 text-slate-300">Sales, inventory, people, payments and reports are organized into one professional workspace.</p></div><div className="mt-8 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text])=><div key={title} className="bg-slate-950 p-6 sm:p-7"><Icon className="h-6 w-6 text-blue-300"/><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></section>
  <section id="how" className="mx-auto max-w-7xl px-4 py-16 sm:px-8"><div className="grid gap-4 lg:grid-cols-3">{[["01","Choose your workspace","Select Shop, School or Gym during account creation."],["02","Add your organization details","Name, phone, location and the details that make the workspace yours."],["03","Work in a focused dashboard","Your modules and navigation are tailored to the organization you selected."]].map(([n,t,x])=><div key={n} className="rounded-3xl border border-slate-200 p-6"><span className="text-sm font-black text-blue-600">{n}</span><h3 className="mt-7 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{x}</p></div>)}</div></section>
  <section id="about" className="border-t bg-slate-50"><div className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Get to know Sahel</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">One professional system for everyday business.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">Sahel helps organizations manage shop sales and inventory, school admissions and records, and gym memberships and payments.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5 text-left"><p className="text-2xl font-black text-blue-600">3+</p><p className="mt-1 text-sm font-bold">Business workflows</p></div><div className="rounded-2xl border bg-white p-5 text-left"><p className="text-2xl font-black text-blue-600">1</p><p className="mt-1 text-sm font-bold">Organized workspace</p></div><div className="rounded-2xl border bg-white p-5 text-left"><p className="text-2xl font-black text-blue-600">24/7</p><p className="mt-1 text-sm font-bold">Access on your devices</p></div></div><p id="install-help" className="mt-6 text-xs text-slate-500">If installation is supported, use <strong>Install Sahel</strong> or your browser's <strong>Add to Home Screen</strong> option.</p></div></section>
  <section className="bg-blue-600"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-12 text-white sm:px-8 sm:py-16 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold text-blue-100">Ready to build your workspace?</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">Start with the tools your organization actually needs.</h2></div><div className="flex flex-col gap-2 sm:flex-row"><button onClick={install} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-black"><Download className="h-4 w-4"/>Install</button><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-black text-blue-700">Get started <ArrowRight className="h-4 w-4"/></Link></div></div></section>
  <footer className="bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm sm:px-8 md:flex-row md:items-center md:justify-between"><img src={sahelLogo} className="h-8 brightness-0 invert" alt="Sahel"/><p>Business management software built for organizations in Somalia.</p><p>© 2026 Sahel. All rights reserved.</p></div></footer>
 </main>
}
