import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Check, ChevronDown, CreditCard, Globe2, Menu, Package, ReceiptText, ShieldCheck, ShoppingCart, Smartphone, Sparkles, Store, TrendingUp, WalletCards, X } from "lucide-react";
import sahelLogo from "../assets/sahel_logo_english.svg";

const WA_URL = "https://wa.me/252624407283?text=I%20want%20to%20learn%20more%20about%20Sahel";
const METRICS = [
  { key: "sales", value: "$1,840", change: "+12.4%", bars: [38, 53, 43, 68, 55, 84, 72, 100] },
  { key: "stock", value: "$12,480", change: "124 items", bars: [55, 48, 63, 58, 74, 70, 88, 94] },
  { key: "credit", value: "$2,160", change: "18 customers", bars: [34, 44, 58, 52, 70, 65, 78, 88] }
];

const COPY = {
  en: {
    name: "English", nav: ["Features", "How it works", "Businesses", "FAQ"], login: "Log in", start: "Get started",
    hero: { tag: "Business management, made for Somalia", title: "A clearer way to run your business.", body: "Sales, stock, customer credit, expenses and reports—together in one simple workspace built for Somali businesses.", primary: "Start with Sahel", secondary: "Explore the system", note: ["Built for mobile", "Three languages", "Clear daily records"] },
    dash: { title: "Business overview", today: "Today's performance", sales: "Today's sales", stock: "Stock value", credit: "Customer credit", trend: "Sales performance", live: "Live business view", updated: "Your records are up to date" },
    proof: { title: "The confidence to make every next decision.", body: "Move from notebooks and scattered receipts to a clear, reliable view of your business—at any moment." },
    features: { tag: "Everything connected", title: "The workday, in one calm system.", body: "Designed around the tasks business owners actually do, without complicated software.", items: [["Sales & transactions", "Record every sale quickly and keep a dependable history."], ["Inventory control", "See what is moving, what is low, and what deserves attention."], ["Customer credit", "Keep balances organized so outstanding credit never disappears."], ["Expenses & profit", "Understand where money goes and how the business performs."], ["Clear receipts", "Create customer-ready receipts and keep records in order."], ["Reports & insight", "Turn daily activity into useful business decisions."]] },
    steps: { tag: "A simple start", title: "From setup to insight in three steps.", items: [["01", "Create your workspace", "Set up your business in the way that works for you."], ["02", "Add products and customers", "Bring your important information into one organized place."], ["03", "Record, review, grow", "Use a clearer daily picture to make confident decisions."]] },
    industries: { tag: "Built to adapt", title: "One platform. Different kinds of business.", items: [["Retail shops", "Manage sales, stock, expenses and customer credit."], ["Wholesalers", "Keep product movement and customer balances organized."], ["Service businesses", "Track transactions, expenses and receipts without complexity."]] },
    security: { tag: "Built for trust", title: "Your business deserves a serious home for its records.", body: "Sahel puts your day-to-day information in one organized place, with clear account access and a mobile-first experience.", points: ["Clear account access", "Organized business records", "Designed for mobile", "Built with local businesses in mind"] },
    faq: { tag: "Questions, answered", title: "Frequently asked questions", items: [["What is Sahel?", "Sahel is a business management platform for handling sales, inventory, customer credit, expenses, receipts and reports in one place."], ["Can I use Sahel on my phone?", "Yes. Sahel is designed for a mobile-first experience, so important business work stays within reach."], ["Which languages does Sahel support?", "The landing page is available in English, Somali and Arabic. Your product language options are available in your account settings."], ["Is Sahel only for shops?", "No. Sahel supports common retail, wholesale and service-business workflows."]] },
    cta: { tag: "Ready when you are", title: "Bring your business into one clear system.", body: "Spend less time chasing records and more time moving your business forward.", primary: "Get started", secondary: "Talk to Sahel" },
    footer: "Business management software built for Somalia.", rights: "© 2026 Sahel. All rights reserved."
  },
  so: {
    name: "Soomaali", nav: ["Astaamaha", "Sida uu u shaqeeyo", "Ganacsiyada", "Su'aalo"], login: "Gal", start: "Bilow",
    hero: { tag: "Maamulka ganacsiga, oo loo dhisay Soomaaliya", title: "Hab cad oo aad ganacsigaaga u maamusho.", body: "Iibka, bakhaarka, deynta macaamiisha, kharashaadka iyo warbixinnada—dhammaantood hal meel oo fudud, loona dhisay ganacsiyada Soomaaliyeed.", primary: "Ku bilow Sahel", secondary: "Eeg nidaamka", note: ["Mobile-ka loogu talagalay", "Saddex luqadood", "Diiwaanno cad"] },
    dash: { title: "Guudmarka ganacsiga", today: "Waxqabadka maanta", sales: "Iibka maanta", stock: "Qiimaha bakhaarka", credit: "Deynta macaamiisha", trend: "Waxqabadka iibka", live: "Aragti ganacsi oo toos ah", updated: "Diiwaannadaadu waa cusub yihiin" },
    proof: { title: "Kalsoonida go'aan kasta oo xiga.", body: "Ka gudub buugaagta iyo rasiidhada kala yaacsan una gudub aragti cad oo lagu kalsoonaan karo—waqti kasta." },
    features: { tag: "Wax walba way isku xiran yihiin", title: "Maalinta shaqada, hal nidaam oo deggan.", body: "Waxaa loo dhisay hawlaha ganacsatadu dhab ahaan qabtaan, iyada oo aan la isticmaalin software adag.", items: [["Iibka iyo macaamilada", "Si degdeg ah u diiwaan geli iib kasta oo hayso taariikh lagu kalsoonaan karo."], ["Maamulka bakhaarka", "Ogow waxa dhaqaaqaya, waxa yaraaday iyo waxa u baahan fiiro."], ["Deynta macaamiisha", "Si habaysan u kaydi hadhaaga si dayntu aysan u lumin."], ["Kharashaadka iyo faa'iidada", "Faham halka lacagtu u socoto iyo waxqabadka ganacsiga."], ["Rasiidh cad", "Samee rasiid ay macaamiishu fahmaan oo diiwaankaaga habee."], ["Warbixin iyo faham", "Hawlaha maalinlaha ah u beddel go'aanno waxtar leh."]] },
    steps: { tag: "Bilow fudud", title: "Laga bilaabo dejinta ilaa fahamka, saddex tallaabo.", items: [["01", "Samee goobtaada", "U deji ganacsigaaga sida adiga kuu shaqaysa."], ["02", "Ku dar alaabta iyo macaamiisha", "Xogtaada muhiimka ah hal meel oo habaysan ku keen."], ["03", "Diiwaan geli, eeg, kobci", "Aragti maalinle cad ku samee go'aanno kalsooni leh."]] },
    industries: { tag: "La qabsan kara", title: "Hal platform. Ganacsiyo kala duwan.", items: [["Dukaamada tafaariiqda", "Maamul iibka, bakhaarka, kharashaadka iyo deynta."], ["Jumlada", "Habee dhaqdhaqaaqa alaabta iyo hadhaaga macaamiisha."], ["Ganacsiyada adeegga", "La soco macaamilada, kharashaadka iyo rasiidhada si fudud."]] },
    security: { tag: "Loo dhisay kalsooni", title: "Ganacsigaagu wuxuu mudan yahay meel dhab ah oo diiwaannadiisa ah.", body: "Sahel waxay xogtaada maalinlaha ah gelisaa hal meel oo habaysan, gelitaan cad leh, kuna shaqaysa mobile-ka.", points: ["Gelitaan akoon oo cad", "Diiwaanno ganacsi oo habaysan", "Mobile-ka loogu talagalay", "Loo dhisay ganacsiyada maxalliga ah"] },
    faq: { tag: "Jawaabaha su'aalaha", title: "Su'aalaha inta badan la isweydiiyo", items: [["Waa maxay Sahel?", "Sahel waa platform maamulka ganacsiga oo hal meel ku maamula iibka, bakhaarka, deynta, kharashaadka, rasiidhada iyo warbixinnada."], ["Sahel ma ku isticmaali karaa telefoon?", "Haa. Sahel waxaa loogu talagalay mobile-first si shaqada ganacsigaagu kuu ag joogto."], ["Luqadee ayay Sahel taageertaa?", "Bogga hore wuxuu ku jiraa English, Soomaali iyo Carabi. Luqadaha badeecadda waxaad ka heli kartaa dejimaha akoonkaaga."], ["Sahel dukaamo oo keliya ma u tahay?", "Maya. Waxay taageertaa tafaariiq, jumlo iyo hawlaha ganacsiyada adeegga."]] },
    cta: { tag: "Markaad diyaar tahay", title: "Ganacsigaaga geli hal nidaam oo cad.", body: "Waqti yar ku bixi raadinta diiwaannada, waqti badanna ku bixi kobcinta ganacsigaaga.", primary: "Bilow", secondary: "La hadal Sahel" },
    footer: "Software-ka maamulka ganacsiga ee loo dhisay Soomaaliya.", rights: "© 2026 Sahel. Xuquuqda oo dhan way dhowran tahay."
  },
  ar: {
    name: "العربية", nav: ["المزايا", "كيف يعمل", "الأعمال", "الأسئلة"], login: "تسجيل الدخول", start: "ابدأ الآن",
    hero: { tag: "إدارة أعمال صُممت للصومال", title: "طريقة أوضح لإدارة عملك.", body: "المبيعات والمخزون وديون العملاء والمصروفات والتقارير—كلها في مساحة عمل بسيطة واحدة صُممت للشركات الصومالية.", primary: "ابدأ مع سهل", secondary: "استكشف النظام", note: ["مصمم للهاتف", "ثلاث لغات", "سجلات يومية واضحة"] },
    dash: { title: "نظرة عامة على الأعمال", today: "أداء اليوم", sales: "مبيعات اليوم", stock: "قيمة المخزون", credit: "ديون العملاء", trend: "أداء المبيعات", live: "عرض مباشر للأعمال", updated: "سجلاتك محدثة" },
    proof: { title: "الثقة لاتخاذ كل قرار قادم.", body: "انتقل من الدفاتر والإيصالات المتفرقة إلى رؤية واضحة وموثوقة لأعمالك في أي وقت." },
    features: { tag: "كل شيء مترابط", title: "يوم العمل، في نظام هادئ واحد.", body: "مصمم للمهام التي يقوم بها أصحاب الأعمال فعلاً، بدون برامج معقدة.", items: [["المبيعات والمعاملات", "سجّل كل عملية بيع بسرعة واحتفظ بسجل موثوق."], ["إدارة المخزون", "اعرف ما يتحرك وما ينقص وما يحتاج إلى اهتمام."], ["ديون العملاء", "نظم الأرصدة حتى لا تضيع الديون المستحقة."], ["المصروفات والربح", "افهم أين تذهب الأموال وكيف يعمل نشاطك."], ["إيصالات واضحة", "أنشئ إيصالات جاهزة للعملاء وحافظ على ترتيب سجلاتك."], ["تقارير ورؤى", "حوّل النشاط اليومي إلى قرارات مفيدة."]] },
    steps: { tag: "بداية بسيطة", title: "من الإعداد إلى الرؤية في ثلاث خطوات.", items: [["01", "أنشئ مساحة عملك", "أعد عملك بالطريقة المناسبة لك."], ["02", "أضف المنتجات والعملاء", "اجمع معلوماتك المهمة في مكان واحد منظم."], ["03", "سجّل وراجع ونَمِّ", "استخدم صورة يومية أوضح لاتخاذ قرارات واثقة."]] },
    industries: { tag: "مصمم للتكيف", title: "منصة واحدة. أعمال مختلفة.", items: [["متاجر التجزئة", "أدر المبيعات والمخزون والمصروفات وديون العملاء."], ["تجارة الجملة", "نظم حركة المنتجات وأرصدة العملاء."], ["الأعمال الخدمية", "تابع المعاملات والمصروفات والإيصالات بسهولة."]] },
    security: { tag: "مصمم للثقة", title: "يستحق عملك مكاناً جاداً لسجلاته.", body: "يضع سهل معلوماتك اليومية في مكان واحد منظم، مع وصول واضح للحساب وتجربة مصممة للهاتف.", points: ["وصول واضح للحساب", "سجلات أعمال منظمة", "مصمم للهاتف", "مصمم للأعمال المحلية"] },
    faq: { tag: "إجابات واضحة", title: "الأسئلة المتكررة", items: [["ما هو سهل؟", "سهل منصة لإدارة الأعمال تساعدك على إدارة المبيعات والمخزون وديون العملاء والمصروفات والإيصالات والتقارير في مكان واحد."], ["هل يمكنني استخدام سهل على الهاتف؟", "نعم. صُمم سهل بتجربة تركز على الهاتف لتبقى أعمالك المهمة في متناول يدك."], ["ما اللغات التي يدعمها سهل؟", "الصفحة متاحة بالإنجليزية والصومالية والعربية. تتوفر خيارات لغة المنتج في إعدادات حسابك."], ["هل سهل للمتاجر فقط؟", "لا. يدعم سهل سير العمل الشائع في التجزئة والجملة والأعمال الخدمية."]] },
    cta: { tag: "حين تكون جاهزاً", title: "اجمع عملك في نظام واضح واحد.", body: "اقضِ وقتاً أقل في البحث عن السجلات ووقتاً أكثر في تطوير عملك.", primary: "ابدأ الآن", secondary: "تحدث مع سهل" },
    footer: "برنامج لإدارة الأعمال صُمم للصومال.", rights: "© 2026 سهل. جميع الحقوق محفوظة."
  }
};

function Reveal({ children, className = "" }) { return <div className={`reveal ${className}`}>{children}</div>; }
function IconFor({ index, className }) { const icons = [ShoppingCart, Package, CreditCard, WalletCards, ReceiptText, BarChart3]; const Icon = icons[index % icons.length]; return <Icon className={className} />; }

export default function SahelLanding() {
  const [lang, setLang] = useState(() => localStorage.getItem("sahel-landing-language") || "en");
  const [menuOpen, setMenuOpen] = useState(false);
  const [faq, setFaq] = useState(-1);
  const [metric, setMetric] = useState(0);
  const t = useMemo(() => COPY[lang], [lang]);
  const isRTL = lang === "ar";
  const active = METRICS[metric];

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: 0.12 });
    document.querySelectorAll(".reveal").forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("sahel-landing-language", lang);
    document.documentElement.lang = lang; document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.title = lang === "ar" ? "سهل — إدارة الأعمال في الصومال" : lang === "so" ? "Sahel — Maamulka Ganacsiga ee Soomaaliya" : "Sahel — Business Management Software for Somalia";
    const description = lang === "ar" ? "سهل هو برنامج إدارة الأعمال في الصومال للمبيعات والمخزون والديون والمصروفات والتقارير." : lang === "so" ? "Sahel waa software maamulka ganacsiga ee Soomaaliya." : "Sahel is business management software for Somalia: sales, inventory, credit, expenses and reports.";
    let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement("meta"); meta.name = "description"; document.head.appendChild(meta); } meta.content = description;
    document.getElementById("sahel-landing-schema")?.remove();
    const schema = document.createElement("script"); schema.id = "sahel-landing-schema"; schema.type = "application/ld+json"; schema.textContent = JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"Sahel",applicationCategory:"BusinessApplication",operatingSystem:"Web, Android",url:"https://mysahelapp.com/",description,inLanguage:["en","so","ar"],areaServed:{"@type":"Country",name:"Somalia"}}); document.head.appendChild(schema);
  }, [lang, isRTL]);

  useEffect(() => { const timer = window.setInterval(() => setMetric((current) => (current + 1) % METRICS.length), 3800); return () => window.clearInterval(timer); }, []);

  const chooseLanguage = (next) => { setLang(next); setMenuOpen(false); setFaq(-1); };

  return <div className="min-h-screen overflow-x-hidden bg-white text-slate-950 antialiased">
    <style>{`
      html { scroll-behavior:smooth } .sahel-grid{background-image:linear-gradient(rgba(37,99,235,.075) 1px,transparent 1px),linear-gradient(90deg,rgba(37,99,235,.075) 1px,transparent 1px);background-size:38px 38px}
      .reveal{opacity:0;transform:translateY(22px);transition:opacity .65s ease,transform .65s cubic-bezier(.2,.7,.2,1)}.reveal.is-visible{opacity:1;transform:translateY(0)}
      @keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@keyframes orbit{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:.35;transform:scale(1)}50%{opacity:.72;transform:scale(1.08)}}@keyframes glow{0%,100%{opacity:.4}50%{opacity:.85}}
      .float{animation:float 6s ease-in-out infinite}.orbit{animation:orbit 24s linear infinite}.pulse{animation:pulse 5s ease-in-out infinite}.glow{animation:glow 3s ease-in-out infinite}
      @media (prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal{opacity:1;transform:none;transition:none}.float,.orbit,.pulse,.glow{animation:none}}
    `}</style>
    <div className="h-1 bg-gradient-to-r from-blue-700 via-blue-500 to-orange-500" />
    <header className="sticky top-0 z-50 border-b border-blue-100 bg-white/90 backdrop-blur-xl">
      <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8">
        <Link to="/" aria-label="Sahel home"><img src={sahelLogo} alt="Sahel" className="h-9 w-auto" /></Link>
        <nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">
          {["features","how","industries","faq"].map((id, i) => <a key={id} href={`#${id}`} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 transition hover:bg-blue-50 hover:text-blue-700">{t.nav[i]}</a>)}
          <div className="mx-3 h-6 w-px bg-slate-200" />
          <div className="flex rounded-full bg-slate-100 p-1" aria-label="Language selector">{["en","so","ar"].map((code) => <button key={code} onClick={() => chooseLanguage(code)} aria-pressed={lang === code} className={`rounded-full px-2.5 py-1.5 text-xs font-extrabold transition ${lang === code ? "bg-blue-600 text-white shadow-sm" : "text-slate-500 hover:text-blue-700"}`}>{code.toUpperCase()}</button>)}</div>
          <Link to="/login" className="ms-3 rounded-lg px-3 py-2 text-sm font-bold text-blue-700 transition hover:bg-blue-50">{t.login}</Link>
          <Link to="/signup" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-[0_10px_22px_rgba(37,99,235,.25)] transition hover:-translate-y-0.5 hover:bg-blue-700">{t.start}</Link>
        </nav>
        <button onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen} className="rounded-xl p-2 text-blue-700 lg:hidden">{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <div className="border-t border-blue-100 bg-white px-5 py-4 lg:hidden"><div className="space-y-1">{["features","how","industries","faq"].map((id, i) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)} className="block rounded-xl px-3 py-3 text-sm font-bold text-slate-700 hover:bg-blue-50">{t.nav[i]}</a>)}<div className="grid grid-cols-3 gap-2 py-3">{["en","so","ar"].map((code) => <button key={code} onClick={() => chooseLanguage(code)} className={`rounded-xl py-2 text-xs font-extrabold ${lang === code ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{COPY[code].name}</button>)}</div><div className="grid grid-cols-2 gap-2"><Link to="/login" className="rounded-xl border border-blue-200 py-3 text-center text-sm font-bold text-blue-700">{t.login}</Link><Link to="/signup" className="rounded-xl bg-blue-600 py-3 text-center text-sm font-bold text-white">{t.start}</Link></div></div></div>}
    </header>
    <main>
      <section className="relative isolate overflow-hidden bg-gradient-to-b from-blue-50 via-white to-white">
        <div className="sahel-grid absolute inset-0 mask-image-gradient opacity-60" /><div className="pulse absolute -left-32 top-12 h-72 w-72 rounded-full bg-blue-400/20 blur-3xl" /><div className="pulse absolute -right-24 top-24 h-80 w-80 rounded-full bg-orange-300/20 blur-3xl" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-[1fr_1.04fr] lg:px-8 lg:py-28">
          <Reveal className="max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white/80 px-3.5 py-2 text-xs font-extrabold text-blue-700 shadow-sm"><Sparkles size={14} className="text-orange-500" />{t.hero.tag}</div><h1 className="text-4xl font-black leading-[1.06] tracking-tight text-slate-950 sm:text-5xl lg:text-[4.35rem]">{t.hero.title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">{t.hero.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-extrabold text-white shadow-[0_15px_30px_rgba(37,99,235,.26)] transition hover:-translate-y-1 hover:bg-blue-700">{t.hero.primary}<ArrowRight size={17} className={isRTL ? "rotate-180" : ""} /></Link><a href="#how" className="inline-flex items-center justify-center gap-2 rounded-xl border border-blue-200 bg-white px-6 py-3.5 text-sm font-extrabold text-blue-700 transition hover:border-blue-300 hover:bg-blue-50">{t.hero.secondary}<ChevronDown size={17} /></a></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2">{t.hero.note.map((item) => <span key={item} className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-600"><Check size={15} className="text-orange-500" />{item}</span>)}</div></Reveal>
          <Reveal className="relative mx-auto w-full max-w-xl"><div className="float absolute -left-4 top-8 hidden h-20 w-20 rounded-3xl border border-blue-100 bg-white/80 shadow-lg sm:block" /><div className="orbit absolute -right-9 -top-10 hidden h-32 w-32 rounded-full border border-dashed border-orange-300/70 md:block" /><div className="relative overflow-hidden rounded-[2rem] border border-blue-100 bg-white p-3 shadow-[0_30px_80px_rgba(30,64,175,.18)] sm:p-5"><div className="rounded-[1.35rem] bg-gradient-to-br from-blue-700 to-blue-950 p-4 text-white sm:p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-200">{t.dash.live}</p><h2 className="mt-1 text-xl font-black">{t.dash.title}</h2></div><div className="glow rounded-xl bg-white/10 p-2.5 text-orange-300"><TrendingUp size={19} /></div></div><div className="mt-5 grid grid-cols-3 gap-2">{METRICS.map((item, index) => <button key={item.key} onClick={() => setMetric(index)} className={`rounded-xl border p-3 text-start transition ${metric === index ? "border-orange-300 bg-white/15 shadow-lg" : "border-white/10 bg-white/[.06] hover:bg-white/10"}`}><p className="text-[10px] font-bold text-blue-200">{t.dash[item.key]}</p><p className="mt-1 text-sm font-black sm:text-base">{item.value}</p><p className={`mt-1 text-[10px] font-bold ${index === 0 ? "text-orange-300" : "text-blue-200"}`}>{item.change}</p></button>)}</div><div className="mt-4 rounded-xl bg-white p-4 text-slate-900"><div className="flex items-center justify-between"><p className="text-xs font-extrabold">{t.dash.trend}</p><span className="rounded-full bg-orange-50 px-2 py-1 text-[10px] font-extrabold text-orange-600">{active.change}</span></div><div className="mt-5 flex h-24 items-end gap-1.5">{active.bars.map((height, index) => <div key={index} className="flex-1 rounded-t-md bg-gradient-to-t from-blue-700 to-blue-400 transition-all duration-700" style={{ height: `${height}%`, transitionDelay: `${index * 45}ms` }} />)}</div><div className="mt-3 flex items-center gap-2 rounded-lg bg-blue-50 px-2.5 py-2 text-[11px] font-bold text-blue-700"><Check size={14} className="text-orange-500" />{t.dash.updated}</div></div></div></div></Reveal>
        </div>
      </section>
      <section className="border-y border-blue-100 bg-blue-700 py-14 text-white"><Reveal className="mx-auto max-w-4xl px-5 text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-300">{t.dash.today}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.proof.title}</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-blue-100">{t.proof.body}</p></Reveal></section>
      <section id="features" className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-600">{t.features.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.features.title}</h2><p className="mt-4 leading-7 text-slate-600">{t.features.body}</p></Reveal><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{t.features.items.map(([title, body], i) => <Reveal key={title}><article className="group h-full rounded-2xl border border-blue-100 bg-white p-6 transition duration-300 hover:-translate-y-2 hover:border-blue-200 hover:shadow-[0_18px_42px_rgba(37,99,235,.14)]"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600 transition group-hover:scale-110 group-hover:bg-blue-600 group-hover:text-white"><IconFor index={i} className="h-5 w-5" /></div><h3 className="mt-5 text-base font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p><div className="mt-5 flex items-center gap-1 text-xs font-extrabold text-blue-600 opacity-0 transition group-hover:opacity-100">{t.hero.secondary}<ArrowRight size={14} className={isRTL ? "rotate-180" : ""} /></div></article></Reveal>)}</div></div></section>
      <section id="how" className="relative overflow-hidden bg-slate-950 py-20 text-white sm:py-24"><div className="absolute inset-0 sahel-grid opacity-20" /><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><Reveal className="mx-auto max-w-2xl text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-300">{t.steps.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.steps.title}</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{t.steps.items.map(([number,title,body], i) => <Reveal key={number}><article className="relative h-full overflow-hidden rounded-2xl border border-white/10 bg-white/[.05] p-7 backdrop-blur transition hover:-translate-y-1 hover:bg-white/[.08]"><span className="text-5xl font-black text-blue-400/35">{number}</span><div className="absolute end-5 top-7 flex h-8 w-8 items-center justify-center rounded-full bg-orange-400 text-sm font-black text-slate-950">{i + 1}</div><h3 className="mt-7 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{body}</p></article></Reveal>)}</div></div></section>
      <section id="industries" className="bg-blue-50 py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Reveal className="mx-auto max-w-2xl text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-600">{t.industries.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.industries.title}</h2></Reveal><div className="mt-10 grid gap-4 md:grid-cols-3">{t.industries.items.map(([title,body],i) => <Reveal key={title}><article className="h-full rounded-2xl border border-blue-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-600 text-white"><IconFor index={i} className="h-5 w-5" /></div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article></Reveal>)}</div></div></section>
      <section className="bg-white py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><Reveal><div className="inline-flex rounded-2xl bg-orange-50 p-4 text-orange-600"><ShieldCheck size={32} /></div><p className="mt-6 text-xs font-extrabold uppercase tracking-[.18em] text-orange-600">{t.security.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.security.title}</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">{t.security.body}</p></Reveal><div className="grid gap-3 sm:grid-cols-2">{t.security.points.map((point) => <Reveal key={point}><div className="flex items-center gap-3 rounded-2xl border border-blue-100 bg-blue-50/50 p-5 transition hover:border-blue-200 hover:bg-white hover:shadow-md"><span className="rounded-full bg-white p-2 text-blue-600 shadow-sm"><Check size={16} /></span><span className="text-sm font-extrabold text-slate-800">{point}</span></div></Reveal>)}</div></div></section>
      <section id="faq" className="bg-slate-50 py-20 sm:py-24"><div className="mx-auto max-w-3xl px-5"><Reveal className="text-center"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-600">{t.faq.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{t.faq.title}</h2></Reveal><div className="mt-10 space-y-3">{t.faq.items.map(([question, answer], index) => { const open = faq === index; return <Reveal key={question}><div className="overflow-hidden rounded-2xl border border-blue-100 bg-white"><button onClick={() => setFaq(open ? -1 : index)} aria-expanded={open} className="flex w-full items-center justify-between gap-4 p-5 text-start font-extrabold text-slate-900"><span>{question}</span><ChevronDown className={`shrink-0 text-blue-600 transition ${open ? "rotate-180" : ""}`} size={19} /></button><div className={`grid transition-[grid-template-rows] duration-300 ${open ? "grid-rows-[1fr]" : "grid-rows-[0fr]"}`}><p className="overflow-hidden border-t border-blue-50 px-5 text-sm leading-6 text-slate-600"><span className="block py-4">{answer}</span></p></div></div></Reveal> })}</div></div></section>
      <section className="relative overflow-hidden bg-blue-700 py-20 text-white"><div className="absolute inset-0 sahel-grid opacity-20" /><div className="relative mx-auto max-w-4xl px-5 text-center"><Reveal><p className="text-xs font-extrabold uppercase tracking-[.18em] text-orange-300">{t.cta.tag}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">{t.cta.title}</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-blue-100">{t.cta.body}</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/signup" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-7 py-3.5 text-sm font-extrabold text-blue-700 transition hover:-translate-y-1 hover:bg-blue-50">{t.cta.primary}<ArrowRight size={16} className={isRTL ? "rotate-180" : ""} /></Link><a href={WA_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/30 px-7 py-3.5 text-sm font-extrabold transition hover:bg-white/10"><Smartphone size={16} />{t.cta.secondary}</a></div></Reveal></div></section>
    </main>
    <footer className="bg-slate-950 py-10 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-5 sm:flex-row sm:items-end lg:px-8"><div><img src={sahelLogo} alt="Sahel" className="h-9 w-auto brightness-0 invert" /><p className="mt-3 text-sm text-slate-400">{t.footer}</p></div><div className="text-sm text-slate-500">{t.rights}</div></div></footer>
    <a href={WA_URL} target="_blank" rel="noopener noreferrer" aria-label="Contact Sahel on WhatsApp" className="fixed bottom-5 end-5 z-40 flex h-12 w-12 items-center justify-center rounded-full bg-[#25D366] text-white shadow-[0_12px_28px_rgba(37,211,102,.32)] transition hover:scale-110"><Smartphone size={21} /></a>
  </div>;
}
