import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Globe2, MapPin, Phone, Store, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiRequest } from "../lib/api";
import { saveSession } from "../lib/auth";
import sahelIcon from "../assets/sahel_logo_icon_only.svg";

const COPY = {
  en:{ title:"Set up your business", sub:"A few details and you are ready to go.", shop:"Shop name", phone:"Phone number", location:"Location / City", exampleShop:"e.g. Hassan General Store", exampleLocation:"e.g. Mogadishu, Somalia", phoneNote:"Used only to help with your account.", start:"Start using Sahel", saving:"Creating your business…", update:"You can update these details anytime in Settings.", required:"Please complete your shop name, phone number and location.", done:"You're all set!", doneText:"is ready. Taking you to your dashboard…", close:"Close message" },
  so:{ title:"Deji ganacsigaaga", sub:"Faahfaahin yar kadib waad diyaar tahay.", shop:"Magaca dukaanka", phone:"Lambarka telefoonka", location:"Goobta / Magaalada", exampleShop:"tusaale: Dukaanka Xasan", exampleLocation:"tusaale: Muqdisho, Soomaaliya", phoneNote:"Waxaa loo isticmaalaa oo keliya caawinta akoonkaaga.", start:"Bilow isticmaalka Sahel", saving:"Ganacsigaaga ayaa la samaynayaa…", update:"Faahfaahintan mar kasta waad ka beddeli kartaa Dejinta.", required:"Fadlan buuxi magaca dukaanka, telefoonka iyo goobta.", done:"Waad diyaar tahay!", doneText:"waa diyaar. Waxaa lagu geynayaa dashboard-kaaga…", close:"Xir farriinta" },
  ar:{ title:"أعدّ نشاطك التجاري", sub:"بعض التفاصيل وتصبح جاهزاً للبدء.", shop:"اسم المتجر", phone:"رقم الهاتف", location:"الموقع / المدينة", exampleShop:"مثال: متجر حسن العام", exampleLocation:"مثال: مقديشو، الصومال", phoneNote:"يُستخدم فقط للمساعدة بشأن حسابك.", start:"ابدأ استخدام سهل", saving:"جارٍ إنشاء نشاطك…", update:"يمكنك تحديث هذه التفاصيل في أي وقت من الإعدادات.", required:"يرجى إكمال اسم المتجر ورقم الهاتف والموقع.", done:"أنت جاهز!", doneText:"جاهز. جارٍ نقلك إلى لوحة التحكم…", close:"إغلاق الرسالة" }
};
function Field({icon:Icon,label,...props}) { return <label><span className="mb-1.5 block text-xs font-black uppercase tracking-wide text-slate-500">{label} <b className="text-orange-500">*</b></span><span className="flex h-12 items-center gap-3 rounded-xl border border-blue-100 bg-white px-4 shadow-sm transition focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-100"><Icon className="h-4 w-4 shrink-0 text-blue-500"/><input aria-label={label} className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-slate-400" {...props}/></span></label>; }

export default function Onboarding() {
  const navigate=useNavigate(), [lang,setLang]=useState(()=>localStorage.getItem("sahel-auth-language")||"en"), [saving,setSaving]=useState(false), [message,setMessage]=useState(""), [complete,setComplete]=useState(false), [form,setForm]=useState({shop_name:"",phone:"",location:""});
  const t=useMemo(()=>COPY[lang],[lang]), rtl=lang==="ar";
  useEffect(()=>{localStorage.setItem("sahel-auth-language",lang);document.documentElement.lang=lang;document.documentElement.dir=rtl?"rtl":"ltr";},[lang,rtl]);
  const set=(key,value)=>setForm((old)=>({...old,[key]:value}));
  async function submit(e){e.preventDefault();if(!form.shop_name.trim()||!form.phone.trim()||!form.location.trim()){setMessage(t.required);return;}setSaving(true);try{const response=await apiRequest("/auth/setup-shop",{method:"POST",body:JSON.stringify({shop_name:form.shop_name.trim(),phone:form.phone.trim(),location:form.location.trim()})});saveSession(response.data);setComplete(true);setTimeout(()=>navigate("/dashboard",{replace:true}),1800);}catch(error){setMessage(error.message||t.required);}finally{setSaving(false);}}
  const active=(code)=>"rounded-full px-2.5 py-1.5 text-xs font-black transition "+(lang===code?"bg-blue-600 text-white shadow-sm":"text-slate-500 hover:text-blue-700");
  if(complete)return <main className="min-h-screen bg-slate-50 p-4"><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-md items-center"><div className="w-full rounded-3xl border border-blue-100 bg-white p-8 text-center shadow-[0_28px_70px_rgba(30,64,175,.16)]"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-blue-50"><CheckCircle2 className="h-9 w-9 text-blue-600"/></div><h1 className="mt-5 text-2xl font-black">{t.done}</h1><p className="mt-2 text-sm leading-6 text-slate-500"><strong>{form.shop_name}</strong> {t.doneText}</p></div></div></main>;
  return <main className="relative min-h-screen overflow-hidden bg-slate-50 p-4 sm:p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(37,99,235,.16),transparent_24%),radial-gradient(circle_at_85%_85%,rgba(249,115,22,.13),transparent_24%)]"/><div className="relative mx-auto flex min-h-[calc(100vh-2rem)] max-w-lg items-center"><section className="w-full rounded-[2rem] border border-blue-100 bg-white p-6 shadow-[0_28px_85px_rgba(30,64,175,.16)] sm:p-9"><div className="flex items-start justify-between gap-4"><div><img src={sahelIcon} alt="Sahel" className="h-12 w-12"/><h1 className="mt-5 text-3xl font-black text-slate-950">{t.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{t.sub}</p></div><div className="flex rounded-full bg-slate-100 p-1">{["en","so","ar"].map((code)=><button key={code} onClick={()=>setLang(code)} aria-pressed={lang===code} className={active(code)}>{code.toUpperCase()}</button>)}</div></div><form onSubmit={submit} className="mt-8 space-y-4"><Field icon={Store} label={t.shop} placeholder={t.exampleShop} value={form.shop_name} onChange={(e)=>set("shop_name",e.target.value)} required/><Field icon={Phone} label={t.phone} type="tel" placeholder="+252 61 234 5678" value={form.phone} onChange={(e)=>set("phone",e.target.value)} required/><p className="-mt-2 text-xs font-semibold text-slate-400">{t.phoneNote}</p><Field icon={MapPin} label={t.location} placeholder={t.exampleLocation} value={form.location} onChange={(e)=>set("location",e.target.value)} required/><button disabled={saving} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-black text-white shadow-[0_12px_25px_rgba(37,99,235,.28)] transition hover:bg-blue-700 disabled:opacity-60">{saving?t.saving:t.start}<ChevronRight className={"h-4 w-4 "+(rtl?"rotate-180":"")}/></button></form><p className="mt-5 text-center text-xs font-semibold leading-5 text-slate-400">{t.update}</p></section></div>{message&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="relative w-full max-w-sm rounded-2xl bg-white p-6 text-center shadow-2xl"><button onClick={()=>setMessage("")} aria-label={t.close} className="absolute end-4 top-4 p-2 text-slate-400"><X size={18}/></button><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-orange-50 text-orange-600"><Globe2 size={22}/></div><h2 className="mt-4 text-lg font-black">Sahel</h2><p className="mt-2 text-sm leading-6 text-slate-600">{message}</p><button onClick={()=>setMessage("")} className="mt-5 w-full rounded-xl bg-blue-600 py-3 text-sm font-black text-white">OK</button></div></div>}</main>;
}