const jwt = require("jsonwebtoken");
const { supabase, supabaseAdmin } = require("../config/supabase");
const { withRetry } = require("../utils/withRetry");

const PHONE_PATTERN = /^(61|62|68)\d{7}$/;
const VALID_BUSINESS_TYPES = ["shop", "gym", "school", "hospital"];
const normalizePhone = (value = "") => String(value).replace(/\D/g, "");
const normalizeEmail = (value = "") => String(value).trim().toLowerCase();
const signToken = (authId, email, phone, shop) => {
  if (!process.env.JWT_SECRET) throw new Error("Missing JWT_SECRET environment variable.");
  return jwt.sign({ user_id: authId, email, phone: phone || null, shop_id: shop?.id || null, shop_name: shop?.shop_name || null, business_type: shop?.business_type || null, onboarding_required: !shop }, process.env.JWT_SECRET, { expiresIn: "12h" });
};
const getShopForAuthUser = async (authId) => { const { data, error } = await supabaseAdmin.from("shops").select("id, owner_id, shop_name, location, phone, business_type, status, plan, created_at, hear_about, main_problem").eq("owner_id", authId).order("created_at", { ascending: true }).limit(1).maybeSingle(); if (error) throw error; return data || null; };

const signup = async (req,res,next)=>{try{const {email,password,full_name}=req.body;const normalizedEmail=normalizeEmail(email);if(!normalizedEmail||!password)return res.status(400).json({message:"email and password are required."});if(password.length<8)return res.status(400).json({message:"Password must be at least 8 characters."});const {data:authData,error:authError}=await supabaseAdmin.auth.admin.createUser({email:normalizedEmail,password,email_confirm:true,user_metadata:{full_name:String(full_name||"").trim()||null}});if(authError){if(authError.message?.toLowerCase().includes("already"))return res.status(409).json({message:"An account with this email already exists."});throw authError;}const authId=authData.user.id;const token=signToken(authId,normalizedEmail,null,null);res.status(201).json({data:{token,user:{id:authId,email:normalizedEmail,full_name:String(full_name||"").trim()||null},shop:null,onboarding_required:true}})}catch(error){next(error)}};

const login = async (req,res,next)=>{try{const {email,phone,identifier,password,business_type}=req.body;const loginId=String(phone||email||identifier||"").trim();if(!loginId||!password)return res.status(400).json({message:"email and password are required."});const normalizedEmail=normalizeEmail(loginId);const {data:authData,error:authError}=await withRetry(()=>supabase.auth.signInWithPassword({email:normalizedEmail,password}));if(!authError&&authData?.user){const authId=authData.user.id;const shop=await getShopForAuthUser(authId);if(shop?.status==="suspended")return res.status(403).json({message:"This account is suspended."});const token=signToken(authId,authData.user.email,shop?.phone||null,shop);return res.json({data:{token,user:{id:authId,email:authData.user.email,phone:shop?.phone||null,shop_name:shop?.shop_name||null},shop,onboarding_required:!shop}})}const {data:staffData,error:staffError}=await withRetry(()=>supabaseAdmin.rpc("staff_login",{p_email:normalizedEmail,p_password:password}));if(staffError||!staffData)return res.status(401).json({message:"Invalid email or password."});const staff=staffData;const {data:shop,error:shopError}=await supabaseAdmin.from("shops").select("id, shop_name, location, status, plan, business_type").eq("id",staff.shop_id).single();if(shopError||!shop)return res.status(403).json({message:"Workspace not found."});if(shop.status==="suspended")return res.status(403).json({message:"This account is suspended."});const token=jwt.sign({user_id:staff.id,email:staff.email,phone:staff.phone||null,shop_id:staff.shop_id,shop_name:shop.shop_name,business_type:shop.business_type||null,role:staff.role||"staff",is_staff:true,onboarding_required:false},process.env.JWT_SECRET,{expiresIn:"12h"});res.json({data:{token,user:{id:staff.id,email:staff.email,phone:staff.phone||null,name:staff.name,role:staff.role||"staff"},shop,is_staff:true,onboarding_required:false}})}catch(error){next(error)}};

const oauthSession=async(req,res,next)=>{try{const {access_token}=req.body;if(!access_token)return res.status(400).json({message:"access_token is required."});const {data:authData,error:authError}=await withRetry(()=>supabase.auth.getUser(access_token));if(authError||!authData?.user?.email)return res.status(401).json({message:"Invalid Google session."});const authId=authData.user.id;const email=authData.user.email.trim().toLowerCase();const shop=await getShopForAuthUser(authId);if(shop?.status==="suspended")return res.status(403).json({message:"This account is suspended."});const token=signToken(authId,email,null,shop);res.json({data:{token,user:{id:authId,email,shop_name:shop?.shop_name||null},shop,onboarding_required:!shop}})}catch(error){next(error)}};

const setupShop=async(req,res,next)=>{try{const {shop_name,location,phone,business_type,main_problem,hear_about}=req.body;const normalizedPhone=normalizePhone(phone);if(!shop_name?.trim()||!location?.trim()||!business_type)return res.status(400).json({message:"Business name, location, and management type are required."});if(!VALID_BUSINESS_TYPES.includes(business_type))return res.status(400).json({message:`business_type must be one of: ${VALID_BUSINESS_TYPES.join(", ")}.`});if(!PHONE_PATTERN.test(normalizedPhone))return res.status(400).json({message:"Phone must be 9 digits and start with 61, 62, or 68."});const authId=req.user.user_id;const email=req.user.email;const existingShop=await getShopForAuthUser(authId);if(existingShop){const token=signToken(authId,email,existingShop.phone,existingShop);return res.json({data:{token,user:{id:authId,email},shop:existingShop,onboarding_required:false}})}const {data:shop,error:shopError}=await supabaseAdmin.from("shops").insert({owner_id:authId,shop_name:shop_name.trim(),location:location.trim(),phone:normalizedPhone,business_type,main_problem:main_problem?.trim()||null,hear_about:hear_about?.trim()||null,status:"active",plan:"free"}).select("id, owner_id, shop_name, location, phone, business_type, status, plan, created_at, hear_about, main_problem").single();if(shopError)throw shopError;const token=signToken(authId,email,normalizedPhone,shop);res.status(201).json({data:{token,user:{id:authId,email},shop,onboarding_required:false}})}catch(error){next(error)}};

const changePassword=async(req,res,next)=>{try{const {new_password}=req.body;if(!new_password)return res.status(400).json({message:"new_password is required."});if(new_password.length<8)return res.status(400).json({message:"New password must be at least 8 characters."});const {error}=await supabaseAdmin.auth.admin.updateUserById(req.user.user_id,{password:new_password});if(error)throw error;res.json({message:"Password changed."})}catch(error){next(error)}};
const switchShop=async(req,res,next)=>{try{const {shop_id}=req.body;if(!shop_id)return res.status(400).json({message:"shop_id is required."});const {data:shop,error}=await supabaseAdmin.from("shops").select("id, owner_id, shop_name, location, phone, business_type, status, plan").eq("id",shop_id).eq("owner_id",req.user.user_id).single();if(error||!shop)return res.status(403).json({message:"Workspace not found or access denied."});if(shop.status==="suspended")return res.status(403).json({message:"This account is suspended."});const token=signToken(req.user.user_id,req.user.email,shop.phone,shop);res.json({data:{token,user:{id:req.user.user_id,email:req.user.email},shop}})}catch(error){next(error)}};
const staffLogin=async(req,res,next)=>{try{const {email,password}=req.body;if(!email||!password)return res.status(400).json({message:"email and password are required."});const {data,error}=await supabaseAdmin.rpc("staff_login",{p_email:email.trim().toLowerCase(),p_password:password});if(error||!data)return res.status(401).json({message:"Invalid email or password."});const staff=data;const {data:shop,error:shopError}=await supabaseAdmin.from("shops").select("id, shop_name, location, status, plan, business_type").eq("id",staff.shop_id).single();if(shopError||!shop)return res.status(403).json({message:"Workspace not found."});if(shop.status==="suspended")return res.status(403).json({message:"This account is suspended."});const token=jwt.sign({user_id:staff.id,email:staff.email,phone:staff.phone||null,shop_id:staff.shop_id,shop_name:shop.shop_name,business_type:shop.business_type||null,role:staff.role||"staff",is_staff:true,onboarding_required:false},process.env.JWT_SECRET,{expiresIn:"12h"});res.json({data:{token,user:{id:staff.id,email:staff.email,phone:staff.phone||null,name:staff.name,role:staff.role||"staff"},shop,is_staff:true,onboarding_required:false}})}catch(error){next(error)}};
module.exports={changePassword,signup,login,oauthSession,setupShop,switchShop,staffLogin};
