const { supabaseAdmin: supabase } = require("../config/supabase");

const currentMonthStart = () => { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString().slice(0, 10); };
const nextMonthStart = () => { const now = new Date(); return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)).toISOString().slice(0, 10); };
const clean = (value) => typeof value === "string" ? value.trim() : value;
const numberOrZero = (value) => value === "" || value === undefined || value === null ? 0 : Number(value);

const guardianPatch = (guardianType, guardianName) => {
  const name = clean(guardianName) || null;
  return {
    father_name: guardianType === "father" ? name : null,
    mother_name: guardianType === "mother" ? name : null,
    guardian_name: guardianType === "other" ? name : null,
  };
};

const getClasses = async (req,res,next) => { try { const {data,error}=await supabase.from("school_classes").select("*, school_teachers(name)").eq("shop_id",req.user.shop_id).order("level",{ascending:true}).order("name",{ascending:true}); if(error)throw error;res.json({data}); }catch(error){next(error);} };
const createClass = async (req,res,next) => { try { const {name,grade,level="primary",teacher_id}=req.body;if(!clean(name))return res.status(400).json({message:"Class name is required."});if(!["primary","secondary"].includes(level))return res.status(400).json({message:"Level must be primary or secondary."});if(teacher_id){const {data:t,error}=await supabase.from("school_teachers").select("id").eq("id",teacher_id).eq("shop_id",req.user.shop_id).maybeSingle();if(error)throw error;if(!t)return res.status(400).json({message:"Teacher does not belong to this school."});}const {data,error}=await supabase.from("school_classes").insert({shop_id:req.user.shop_id,name:clean(name),grade:clean(grade)||null,level,teacher_id:teacher_id||null}).select("*, school_teachers(name)").single();if(error)throw error;res.status(201).json({message:"Class added.",data}); }catch(error){next(error);} };
const deleteClass = async (req,res,next) => { try {const {error}=await supabase.from("school_classes").delete().eq("id",req.params.id).eq("shop_id",req.user.shop_id);if(error)throw error;res.json({message:"Class removed."});}catch(error){next(error);} };

const getStudents = async (req,res,next) => { try {let query=supabase.from("school_students").select("*, school_classes(name,level,grade)").eq("shop_id",req.user.shop_id);if(req.query.class_id)query=query.eq("class_id",req.query.class_id);if(req.query.search){const search=clean(req.query.search).replace(/[%_]/g,"").replace(/,/g," ");if(search)query=query.or(`name.ilike.%${search}%,registration_no.ilike.%${search}%,father_name.ilike.%${search}%,mother_name.ilike.%${search}%,guardian_name.ilike.%${search}%`);}const {data,error}=await query;if(error)throw error;(data||[]).sort((a,b)=>Number(a.registration_no||0)-Number(b.registration_no||0));res.json({data:data||[]});}catch(error){next(error);} };
const createStudent = async (req,res,next) => { try {const {name,class_id,guardian_type,guardian_name,phone_number,guardian_phone,age,monthly_fee}=req.body;if(!clean(name))return res.status(400).json({message:"Student name is required."});if(!["father","mother","other"].includes(guardian_type))return res.status(400).json({message:"Choose Father, Mother, or Other guardian."});if(!clean(guardian_name))return res.status(400).json({message:"Guardian name is required."});if(age!==undefined&&age!==""&&(!Number.isInteger(Number(age))||Number(age)<1||Number(age)>100))return res.status(400).json({message:"Age must be a valid number between 1 and 100."});if(class_id){const {data:c,error}=await supabase.from("school_classes").select("id").eq("id",class_id).eq("shop_id",req.user.shop_id).maybeSingle();if(error)throw error;if(!c)return res.status(400).json({message:"Class does not belong to this school."});}const {data,error}=await supabase.from("school_students").insert({shop_id:req.user.shop_id,registration_no:null,name:clean(name),class_id:class_id||null,...guardianPatch(guardian_type,guardian_name),phone_number:clean(phone_number)||clean(guardian_phone)||null,guardian_phone:clean(phone_number)||clean(guardian_phone)||null,age:age===""||age===undefined?null:Number(age),monthly_fee:numberOrZero(monthly_fee),status:"active"}).select("*, school_classes(name,level,grade)").single();if(error)throw error;res.status(201).json({message:"Student registered.",data});}catch(error){next(error);} };
const updateStudent = async (req,res,next) => { try {const patch={};["name","class_id","phone_number","guardian_phone","age","monthly_fee","status"].forEach(k=>{if(req.body[k]!==undefined)patch[k]=typeof req.body[k]==="string"?clean(req.body[k])||null:req.body[k];});if(req.body.guardian_type!==undefined||req.body.guardian_name!==undefined){if(!["father","mother","other"].includes(req.body.guardian_type))return res.status(400).json({message:"Choose Father, Mother, or Other guardian."});if(!clean(req.body.guardian_name))return res.status(400).json({message:"Guardian name is required."});Object.assign(patch,guardianPatch(req.body.guardian_type,req.body.guardian_name));}if(patch.age!==undefined&&patch.age!==null&&patch.age!==""&&(!Number.isInteger(Number(patch.age))||Number(patch.age)<1||Number(patch.age)>100))return res.status(400).json({message:"Age must be between 1 and 100."});if(patch.class_id){const {data:c,error}=await supabase.from("school_classes").select("id").eq("id",patch.class_id).eq("shop_id",req.user.shop_id).maybeSingle();if(error)throw error;if(!c)return res.status(400).json({message:"Class does not belong to this school."});}const {data,error}=await supabase.from("school_students").update(patch).eq("id",req.params.id).eq("shop_id",req.user.shop_id).select("*, school_classes(name,level,grade)").single();if(error)throw error;res.json({message:"Student updated.",data});}catch(error){next(error);} };
const deleteStudent = async (req,res,next) => { try {const {error}=await supabase.from("school_students").delete().eq("id",req.params.id).eq("shop_id",req.user.shop_id);if(error)throw error;res.json({message:"Student removed."});}catch(error){next(error);} };

const getTeachers = async (req,res,next) => {try{const {data,error}=await supabase.from("school_teachers").select("*").eq("shop_id",req.user.shop_id).order("created_at",{ascending:false});if(error)throw error;res.json({data});}catch(error){next(error);}};
const createTeacher = async (req,res,next) => {try{const {name,phone,subject,monthly_salary}=req.body;if(!clean(name))return res.status(400).json({message:"Teacher name is required."});const {data,error}=await supabase.from("school_teachers").insert({shop_id:req.user.shop_id,name:clean(name),phone:clean(phone)||null,subject:clean(subject)||null,monthly_salary:numberOrZero(monthly_salary),status:"active"}).select().single();if(error)throw error;res.status(201).json({message:"Teacher added.",data});}catch(error){next(error);}};
const updateTeacher = async (req,res,next) => {try{const patch={};["name","phone","subject","status"].forEach(k=>{if(req.body[k]!==undefined)patch[k]=clean(req.body[k])||null;});if(req.body.monthly_salary!==undefined)patch.monthly_salary=Number(req.body.monthly_salary);const {data,error}=await supabase.from("school_teachers").update(patch).eq("id",req.params.id).eq("shop_id",req.user.shop_id).select().single();if(error)throw error;res.json({message:"Teacher updated.",data});}catch(error){next(error);}};
const deleteTeacher = async (req,res,next) => {try{const {error}=await supabase.from("school_teachers").delete().eq("id",req.params.id).eq("shop_id",req.user.shop_id);if(error)throw error;res.json({message:"Teacher removed."});}catch(error){next(error);}};

const getFeePayments = async (req,res,next) => {try{const {data,error}=await supabase.from("school_fee_payments").select("*, school_students(name,registration_no)").eq("shop_id",req.user.shop_id).order("paid_at",{ascending:false});if(error)throw error;res.json({data});}catch(error){next(error);}};
const getUnpaidFees = async (req,res,next) => {try{const monthStart=currentMonthStart(),monthEnd=nextMonthStart();const [{data:students,error:se},{data:payments,error:pe}]=await Promise.all([supabase.from("school_students").select("id,name,registration_no,monthly_fee").eq("shop_id",req.user.shop_id).eq("status","active"),supabase.from("school_fee_payments").select("student_id").eq("shop_id",req.user.shop_id).gte("paid_for_month",monthStart).lt("paid_for_month",monthEnd)]);if(se)throw se;if(pe)throw pe;const paid=new Set((payments||[]).map(p=>p.student_id));res.json({data:(students||[]).filter(s=>!paid.has(s.id))});}catch(error){next(error);}};
const createFeePayment = async (req,res,next) => {try{const {student_id,amount,payment_method,paid_for_month}=req.body;if(!student_id||Number(amount)<=0)return res.status(400).json({message:"student_id and a positive amount are required."});const {data:student,error:se}=await supabase.from("school_students").select("id").eq("id",student_id).eq("shop_id",req.user.shop_id).maybeSingle();if(se)throw se;if(!student)return res.status(400).json({message:"Student does not belong to this school."});const {data,error}=await supabase.from("school_fee_payments").insert({shop_id:req.user.shop_id,student_id,amount:Number(amount),paid_for_month:paid_for_month||currentMonthStart(),payment_method:payment_method||"cash"}).select("*, school_students(name,registration_no)").single();if(error)throw error;res.status(201).json({message:"Fee payment recorded.",data});}catch(error){next(error);}};
const getSalaryPayments = async (req,res,next) => {try{const {data,error}=await supabase.from("school_teacher_salary_payments").select("*, school_teachers(name)").eq("shop_id",req.user.shop_id).order("paid_at",{ascending:false});if(error)throw error;res.json({data});}catch(error){next(error);}};
const getUnpaidSalaries = async (req,res,next) => {try{const monthStart=currentMonthStart(),monthEnd=nextMonthStart();const [{data:teachers,error:te},{data:payments,error:pe}]=await Promise.all([supabase.from("school_teachers").select("id,name,monthly_salary").eq("shop_id",req.user.shop_id).eq("status","active"),supabase.from("school_teacher_salary_payments").select("teacher_id").eq("shop_id",req.user.shop_id).gte("paid_for_month",monthStart).lt("paid_for_month",monthEnd)]);if(te)throw te;if(pe)throw pe;const paid=new Set((payments||[]).map(p=>p.teacher_id));res.json({data:(teachers||[]).filter(t=>!paid.has(t.id))});}catch(error){next(error);}};
const createSalaryPayment = async (req,res,next) => {try{const {teacher_id,amount,paid_for_month}=req.body;if(!teacher_id||Number(amount)<=0)return res.status(400).json({message:"teacher_id and a positive amount are required."});const {data:teacher,error:te}=await supabase.from("school_teachers").select("id").eq("id",teacher_id).eq("shop_id",req.user.shop_id).maybeSingle();if(te)throw te;if(!teacher)return res.status(400).json({message:"Teacher does not belong to this school."});const {data,error}=await supabase.from("school_teacher_salary_payments").insert({shop_id:req.user.shop_id,teacher_id,amount:Number(amount),paid_for_month:paid_for_month||currentMonthStart()}).select("*, school_teachers(name)").single();if(error)throw error;res.status(201).json({message:"Salary payment recorded.",data});}catch(error){next(error);}};

const getExams = async (req,res,next) => {try{let query=supabase.from("school_exams").select("*, school_classes(id,name,grade,level)").eq("shop_id",req.user.shop_id).order("academic_year",{ascending:false}).order("exam_date",{ascending:false});if(req.query.class_id)query=query.eq("class_id",req.query.class_id);if(req.query.academic_year)query=query.eq("academic_year",req.query.academic_year);const {data,error}=await query;if(error)throw error;res.json({data});}catch(error){next(error);}};
const createExam = async (req,res,next) => {try{const {class_id,term,academic_year,exam_date,name}=req.body;if(!class_id||!term||!academic_year)return res.status(400).json({message:"Class, academic year and term are required."});if(!["term_1","term_2","term_3"].includes(term))return res.status(400).json({message:"Term must be Term 1, Term 2 or Term 3."});const {data:schoolClass,error:ce}=await supabase.from("school_classes").select("id,name,level").eq("id",class_id).eq("shop_id",req.user.shop_id).maybeSingle();if(ce)throw ce;if(!schoolClass)return res.status(400).json({message:"Class does not belong to this school."});const {data,error}=await supabase.from("school_exams").upsert({shop_id:req.user.shop_id,class_id,term,academic_year:clean(academic_year),exam_date:exam_date||null,max_score:100,name:clean(name)||`${schoolClass.name} - ${term.replace("_"," ")}`},{onConflict:"shop_id,class_id,academic_year,term"}).select("*, school_classes(id,name,grade,level)").single();if(error)throw error;res.status(201).json({message:"Term record ready.",data});}catch(error){next(error);}};
const deleteExam = async (req,res,next) => {try{const {error}=await supabase.from("school_exams").delete().eq("id",req.params.id).eq("shop_id",req.user.shop_id);if(error)throw error;res.json({message:"Term record removed."});}catch(error){next(error);}};
const getExamResults = async (req,res,next) => {try{const {data:exam,error:ee}=await supabase.from("school_exams").select("id,class_id,term,academic_year,school_classes(name,level,grade)").eq("id",req.params.id).eq("shop_id",req.user.shop_id).maybeSingle();if(ee)throw ee;if(!exam)return res.status(404).json({message:"Term record not found."});const {data,error}=await supabase.from("school_exam_results").select("id,student_id,subject,score,school_students(name,registration_no)").eq("exam_id",exam.id).eq("shop_id",req.user.shop_id).order("subject");if(error)throw error;res.json({exam,data});}catch(error){next(error);}};
const saveExamResults = async (req,res,next) => {try{const {results}=req.body;if(!Array.isArray(results))return res.status(400).json({message:"results must be an array."});const {data:exam,error:ee}=await supabase.from("school_exams").select("id,class_id,max_score").eq("id",req.params.id).eq("shop_id",req.user.shop_id).maybeSingle();if(ee)throw ee;if(!exam)return res.status(404).json({message:"Term record not found."});const ids=[...new Set(results.map(r=>r.student_id).filter(Boolean))];if(ids.length){const {data:students,error:se}=await supabase.from("school_students").select("id,class_id").eq("shop_id",req.user.shop_id).in("id",ids);if(se)throw se;const valid=new Map((students||[]).map(s=>[s.id,s]));for(const r of results){const st=valid.get(r.student_id),score=Number(r.score);if(!st)return res.status(400).json({message:"A student does not belong to this school."});if(exam.class_id&&st.class_id!==exam.class_id)return res.status(400).json({message:"All results must belong to the selected class."});if(!r.subject||!String(r.subject).trim())return res.status(400).json({message:"Every score needs a subject."});if(!Number.isFinite(score)||score<0||score>Number(exam.max_score))return res.status(400).json({message:`Scores must be between 0 and ${exam.max_score}.`});}}if(!results.length)return res.json({message:"No results to save.",data:[]});const rows=results.map(r=>({shop_id:req.user.shop_id,exam_id:exam.id,student_id:r.student_id,subject:clean(r.subject),score:Number(r.score)}));const {data,error}=await supabase.from("school_exam_results").upsert(rows,{onConflict:"exam_id,student_id,subject"}).select("*");if(error)throw error;res.json({message:"Results saved.",data});}catch(error){next(error);}};
const getStudentExamHistory = async (req,res,next) => {try{const {data:student,error:se}=await supabase.from("school_students").select("id,name,registration_no,class_id,school_classes(name,level,grade)").eq("id",req.params.id).eq("shop_id",req.user.shop_id).maybeSingle();if(se)throw se;if(!student)return res.status(404).json({message:"Student not found."});const {data,error}=await supabase.from("school_exam_results").select("subject,score,school_exams(id,name,term,academic_year,exam_date)").eq("student_id",student.id).eq("shop_id",req.user.shop_id).order("created_at",{ascending:false});if(error)throw error;res.json({student,data});}catch(error){next(error);}};
const getSubjects = async (req,res) => res.json({primary:["Arabic","Science","Math","Technology","Tarbiya","Social Studies","Somali","English"],secondary:["Arabic","Tarbiya","History","Geography","Chemistry","Biology","Technology","Business","Somali","English","Math"]});

module.exports={getClasses,createClass,deleteClass,getStudents,createStudent,updateStudent,deleteStudent,getTeachers,createTeacher,updateTeacher,deleteTeacher,getFeePayments,getUnpaidFees,createFeePayment,getSalaryPayments,getUnpaidSalaries,createSalaryPayment,getExams,createExam,deleteExam,getExamResults,saveExamResults,getStudentExamHistory,getSubjects};
