import React, { useMemo, useState } from "react";
import { ArrowRight, Beaker, CalendarDays, CheckCircle2, ClipboardList, Clock3, FileText, FlaskConical, Plus, Search, ShieldCheck, Stethoscope, UserRound, UsersRound } from "lucide-react";

const patients = [
  { id: "PAT-2026-00125", name: "Ahmed Hassan", age: 36, doctor: "Dr. Ahmed", department: "Internal Medicine", last: "CBC + Blood Glucose" },
  { id: "PAT-2026-00126", name: "Fatima Ali", age: 29, doctor: "Dr. Maryan", department: "Pediatrics", last: "Liver Function" },
  { id: "PAT-2026-00127", name: "Mohamed Yusuf", age: 51, doctor: "Dr. Ahmed", department: "Internal Medicine", last: "HbA1c" },
];
const labRequests = [
  { id: "LAB-2026-00452", patient: "Ahmed Hassan", doctor: "Dr. Ahmed", tests: ["CBC", "Blood Glucose"], status: "Completed", time: "11:42 AM" },
  { id: "LAB-2026-00453", patient: "Fatima Ali", doctor: "Dr. Maryan", tests: ["Liver Function"], status: "Processing", time: "11:18 AM" },
  { id: "LAB-2026-00454", patient: "Mohamed Yusuf", doctor: "Dr. Ahmed", tests: ["HbA1c"], status: "Pending", time: "10:56 AM" },
];
function Stat({ icon: Icon, label, value, note }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="rounded-xl bg-slate-100 p-2.5"><Icon className="h-5 w-5 text-slate-700" /></div><span className="text-xs font-semibold text-slate-400">Today</span></div><p className="mt-4 text-2xl font-black text-slate-950">{value}</p><p className="text-sm font-semibold text-slate-600">{label}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>; }
function Status({ value }) { const map = { Completed: "bg-emerald-50 text-emerald-700", Processing: "bg-amber-50 text-amber-700", Pending: "bg-slate-100 text-slate-600" }; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${map[value] || map.Pending}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{value}</span>; }

export default function HospitalLabWorkflow() {
  const [activeRole, setActiveRole] = useState("doctor");
  const [selected, setSelected] = useState(labRequests[0]);
  const [query, setQuery] = useState("");
  const [showRequest, setShowRequest] = useState(false);
  const filtered = useMemo(() => patients.filter(p => `${p.name} ${p.id} ${p.doctor}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const roleCopy = activeRole === "doctor" ? { title: "Doctor workspace", subtitle: "See your appointments, authorized patients, and laboratory results connected to your clinical work." } : { title: "Laboratory workspace", subtitle: "Process authorized test requests, enter results, and automatically return completed results to the requesting clinical team." };
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-blue-600">Hospital · Clinical workflow</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">{roleCopy.title}</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">{roleCopy.subtitle}</p></div><div className="flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><button onClick={() => setActiveRole("doctor")} className={`rounded-lg px-3 py-2 text-sm font-bold ${activeRole === "doctor" ? "bg-slate-950 text-white" : "text-slate-500"}`}><Stethoscope className="mr-1.5 inline h-4 w-4" />Doctor</button><button onClick={() => setActiveRole("lab")} className={`rounded-lg px-3 py-2 text-sm font-bold ${activeRole === "lab" ? "bg-slate-950 text-white" : "text-slate-500"}`}><FlaskConical className="mr-1.5 inline h-4 w-4" />Laboratory</button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={CalendarDays} label="Appointments" value="8" note="3 waiting · 4 completed" /><Stat icon={UsersRound} label="My patients" value="6" note="Patients assigned today" /><Stat icon={Beaker} label="Lab results" value="4" note="2 ready for review" /><Stat icon={Clock3} label="Pending requests" value="2" note="Awaiting laboratory work" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]">
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-slate-950">Laboratory workflow</h2><p className="text-xs text-slate-400">Every request stays linked to the patient, appointment, requesting doctor and test.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search patient..." className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-400 sm:w-56" /></div></div><div className="divide-y divide-slate-100">{labRequests.map(request => <button key={request.id} onClick={() => setSelected(request)} className={`flex w-full items-center justify-between gap-4 p-5 text-left transition hover:bg-slate-50 ${selected.id === request.id ? "bg-blue-50/50" : ""}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-slate-900">{request.patient}</p><Status value={request.status} /></div><p className="mt-1 text-xs text-slate-400">{request.id} · Requested by {request.doctor} · {request.time}</p><div className="mt-2 flex flex-wrap gap-1.5">{request.tests.map(test => <span key={test} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{test}</span>)}</div></div><ArrowRight className="h-5 w-5 shrink-0 text-slate-300" /></button>)}</div></section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Selected request</p><h2 className="mt-1 text-xl font-black text-slate-950">{selected.patient}</h2></div><div className="rounded-xl bg-blue-50 p-2.5"><Beaker className="h-5 w-5 text-blue-600" /></div></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-3"><span className="text-slate-400">Request</span><b className="text-slate-700">{selected.id}</b></div><div className="flex justify-between gap-3"><span className="text-slate-400">Doctor</span><b className="text-slate-700">{selected.doctor}</b></div><div className="flex justify-between gap-3"><span className="text-slate-400">Status</span><Status value={selected.status} /></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Tests</p><div className="mt-2 space-y-2">{selected.tests.map(test => <div key={test} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><CheckCircle2 className="h-4 w-4 text-emerald-500" />{test}</div>)}</div></div><button onClick={() => setShowRequest(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5"><Plus className="h-4 w-4" />Request laboratory test</button></aside>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-slate-950">Patient clinical timeline</h2><p className="text-xs text-slate-400">Connected journey from appointment to result.</p></div><div className="grid gap-0 md:grid-cols-5">{[["Appointment", "10:00 AM", CalendarDays], ["Consultation", "10:12 AM", Stethoscope], ["Lab request", "10:28 AM", ClipboardList], ["Lab result", "11:42 AM", FlaskConical], ["Doctor review", "Ready", FileText]].map(([label, time, Icon], i) => <div key={label} className="relative border-b border-slate-100 p-5 last:border-0 md:border-b-0 md:border-r md:last:border-r-0"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-100 p-2"><Icon className="h-4 w-4 text-slate-700" /></div><div><p className="text-xs font-bold text-slate-400">STEP {i + 1}</p><p className="text-sm font-bold text-slate-800">{label}</p><p className="text-xs text-slate-500">{time}</p></div></div>{i < 4 && <ArrowRight className="absolute right-[-10px] top-8 z-10 hidden h-5 w-5 rounded-full bg-white text-slate-300 md:block" />}</div>)}</div></section>
    <div className="flex items-start gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-blue-600" /><div><p className="text-sm font-bold text-blue-900">Access is scoped by role and patient relationship.</p><p className="mt-1 text-xs leading-5 text-blue-800">The requesting doctor automatically receives the completed result. Authorized clinicians can see relevant results for assigned patients. Reception does not receive clinical laboratory results.</p></div></div>
    {filtered.length > 0 && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><UserRound className="h-5 w-5 text-slate-500" /><h2 className="font-black text-slate-950">Patients in your authorized scope</h2></div><div className="grid gap-3 md:grid-cols-3">{filtered.map(patient => <div key={patient.id} className="rounded-xl border border-slate-100 p-4"><p className="font-bold text-slate-900">{patient.name}</p><p className="mt-1 text-xs text-slate-400">{patient.id} · {patient.age} years</p><p className="mt-3 text-xs font-semibold text-slate-600">{patient.doctor} · {patient.department}</p><p className="mt-2 text-xs text-slate-400">Latest: {patient.last}</p></div>)}</div></section>}
    {showRequest && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-slate-950">Request laboratory test</h2><p className="text-sm text-slate-400">The result will stay linked to this patient and appointment.</p></div><button onClick={() => setShowRequest(false)} className="rounded-lg px-3 py-2 text-slate-400 hover:bg-slate-100">✕</button></div><div className="mt-5 space-y-4"><label className="block text-sm font-bold text-slate-700">Patient<select className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 font-normal"><option>Ahmed Hassan — PAT-2026-00125</option><option>Mohamed Yusuf — PAT-2026-00127</option></select></label><label className="block text-sm font-bold text-slate-700">Tests<div className="mt-2 grid grid-cols-2 gap-2">{["CBC", "Blood Glucose", "HbA1c", "Liver Function"].map(test => <label key={test} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" defaultChecked={test === "CBC"} />{test}</label>)}</div></label><label className="block text-sm font-bold text-slate-700">Clinical note<textarea className="mt-1.5 min-h-20 w-full rounded-xl border border-slate-200 p-3 font-normal" placeholder="Reason for test..." /></label><button onClick={() => setShowRequest(false)} className="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Send to laboratory</button></div></div></div>}
  </div>;
}
